# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_o/dmem_o.xci
# IP: The module: 'dmem_o' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_o/dmem_o_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem_o'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_o/dmem_o.xci
# IP: The module: 'dmem_o' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_o/dmem_o_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem_o'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
