# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.cache/wt [current_project]
set_property parent.project_path /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.4 [current_project]
set_property ip_repo_paths /home/yuzou/bnn-fpga-k7/VerilogPrj/IP_Repo [current_project]
set_property ip_output_repo /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i.xci
set_property is_locked true [get_files /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.runs/dmem_i_synth_1 -new_name dmem_i -ip [get_ips dmem_i]]

if { $cached_ip eq {} } {

synth_design -top dmem_i -part xc7k325tffg900-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix dmem_i_ dmem_i.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dmem_i_stub.v
 lappend ipCachedFiles dmem_i_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dmem_i_stub.vhdl
 lappend ipCachedFiles dmem_i_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dmem_i_sim_netlist.v
 lappend ipCachedFiles dmem_i_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dmem_i_sim_netlist.vhdl
 lappend ipCachedFiles dmem_i_sim_netlist.vhdl

 config_ip_cache -add -dcp dmem_i.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips dmem_i]
}

rename_ref -prefix_all dmem_i_

write_checkpoint -force -noxdef dmem_i.dcp

catch { report_utilization -file dmem_i_utilization_synth.rpt -pb dmem_i_utilization_synth.pb }

if { [catch {
  file copy -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.runs/dmem_i_synth_1/dmem_i.dcp /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.runs/dmem_i_synth_1/dmem_i.dcp /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.runs/dmem_i_synth_1/dmem_i_stub.v /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.runs/dmem_i_synth_1/dmem_i_stub.vhdl /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.runs/dmem_i_synth_1/dmem_i_sim_netlist.v /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.runs/dmem_i_synth_1/dmem_i_sim_netlist.vhdl /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.ip_user_files/ip/dmem_i]} {
  catch { 
    file copy -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_stub.v /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.ip_user_files/ip/dmem_i
  }
}

if {[file isdir /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.ip_user_files/ip/dmem_i]} {
  catch { 
    file copy -force /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/dmem_i/dmem_i_stub.vhdl /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.ip_user_files/ip/dmem_i
  }
}
