// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bin_dense (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        wt_mem_0_V_address0,
        wt_mem_0_V_ce0,
        wt_mem_0_V_q0,
        wt_mem_1_V_address0,
        wt_mem_1_V_ce0,
        wt_mem_1_V_q0,
        kh_mem_V_address0,
        kh_mem_V_ce0,
        kh_mem_V_q0,
        dmem_0_0_V_address0,
        dmem_0_0_V_ce0,
        dmem_0_0_V_we0,
        dmem_0_0_V_d0,
        dmem_0_0_V_q0,
        dmem_0_1_V_address0,
        dmem_0_1_V_ce0,
        dmem_0_1_V_we0,
        dmem_0_1_V_d0,
        dmem_0_1_V_q0,
        dmem_1_0_V_address0,
        dmem_1_0_V_ce0,
        dmem_1_0_V_we0,
        dmem_1_0_V_d0,
        dmem_1_0_V_q0,
        dmem_1_1_V_address0,
        dmem_1_1_V_ce0,
        dmem_1_1_V_we0,
        dmem_1_1_V_d0,
        dmem_1_1_V_q0,
        layer_type_V,
        d_i_idx_V,
        d_o_idx_V,
        o_index_V,
        n_inputs,
        n_outputs
);

parameter    ap_ST_fsm_state1 = 10'b1;
parameter    ap_ST_fsm_state2 = 10'b10;
parameter    ap_ST_fsm_state3 = 10'b100;
parameter    ap_ST_fsm_pp0_stage0 = 10'b1000;
parameter    ap_ST_fsm_state11 = 10'b10000;
parameter    ap_ST_fsm_state12 = 10'b100000;
parameter    ap_ST_fsm_state13 = 10'b1000000;
parameter    ap_ST_fsm_state14 = 10'b10000000;
parameter    ap_ST_fsm_state15 = 10'b100000000;
parameter    ap_ST_fsm_state16 = 10'b1000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv16_C000 = 16'b1100000000000000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv22_0 = 22'b0000000000000000000000;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv56_0 = 56'b00000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv16_80 = 16'b10000000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_3D = 32'b111101;
parameter    ap_const_lv32_3B = 32'b111011;
parameter    ap_const_lv32_39 = 32'b111001;
parameter    ap_const_lv32_37 = 32'b110111;
parameter    ap_const_lv32_35 = 32'b110101;
parameter    ap_const_lv32_33 = 32'b110011;
parameter    ap_const_lv32_31 = 32'b110001;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_2D = 32'b101101;
parameter    ap_const_lv32_2B = 32'b101011;
parameter    ap_const_lv32_29 = 32'b101001;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_const_lv32_25 = 32'b100101;
parameter    ap_const_lv32_23 = 32'b100011;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_3C = 32'b111100;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv32_34 = 32'b110100;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_2C = 32'b101100;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv32_24 = 32'b100100;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_3E = 32'b111110;
parameter    ap_const_lv32_3A = 32'b111010;
parameter    ap_const_lv32_36 = 32'b110110;
parameter    ap_const_lv32_32 = 32'b110010;
parameter    ap_const_lv32_2E = 32'b101110;
parameter    ap_const_lv32_2A = 32'b101010;
parameter    ap_const_lv32_26 = 32'b100110;
parameter    ap_const_lv32_22 = 32'b100010;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv9_40 = 9'b1000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv6_0 = 6'b000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] wt_mem_0_V_address0;
output   wt_mem_0_V_ce0;
input  [63:0] wt_mem_0_V_q0;
output  [11:0] wt_mem_1_V_address0;
output   wt_mem_1_V_ce0;
input  [63:0] wt_mem_1_V_q0;
output  [5:0] kh_mem_V_address0;
output   kh_mem_V_ce0;
input  [63:0] kh_mem_V_q0;
output  [9:0] dmem_0_0_V_address0;
output   dmem_0_0_V_ce0;
output   dmem_0_0_V_we0;
output  [63:0] dmem_0_0_V_d0;
input  [63:0] dmem_0_0_V_q0;
output  [9:0] dmem_0_1_V_address0;
output   dmem_0_1_V_ce0;
output   dmem_0_1_V_we0;
output  [63:0] dmem_0_1_V_d0;
input  [63:0] dmem_0_1_V_q0;
output  [9:0] dmem_1_0_V_address0;
output   dmem_1_0_V_ce0;
output   dmem_1_0_V_we0;
output  [63:0] dmem_1_0_V_d0;
input  [63:0] dmem_1_0_V_q0;
output  [9:0] dmem_1_1_V_address0;
output   dmem_1_1_V_ce0;
output   dmem_1_1_V_we0;
output  [63:0] dmem_1_1_V_d0;
input  [63:0] dmem_1_1_V_q0;
input  [1:0] layer_type_V;
input  [0:0] d_i_idx_V;
input  [0:0] d_o_idx_V;
input  [15:0] o_index_V;
input  [15:0] n_inputs;
input  [15:0] n_outputs;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg wt_mem_0_V_ce0;
reg wt_mem_1_V_ce0;
reg[5:0] kh_mem_V_address0;
reg kh_mem_V_ce0;
reg[9:0] dmem_0_0_V_address0;
reg dmem_0_0_V_ce0;
reg dmem_0_0_V_we0;
reg[63:0] dmem_0_0_V_d0;
reg[9:0] dmem_0_1_V_address0;
reg dmem_0_1_V_ce0;
reg dmem_0_1_V_we0;
reg[9:0] dmem_1_0_V_address0;
reg dmem_1_0_V_ce0;
reg dmem_1_0_V_we0;
reg[63:0] dmem_1_0_V_d0;
reg[9:0] dmem_1_1_V_address0;
reg dmem_1_1_V_ce0;
reg dmem_1_1_V_we0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [15:0] p_Val2_3_reg_506;
reg   [15:0] p_5_reg_518;
wire   [0:0] d_o_idx_V_read_read_fu_298_p2;
wire   [0:0] tmp_fu_529_p2;
reg   [0:0] tmp_reg_3640;
wire   [16:0] lhs_V_fu_535_p1;
reg   [16:0] lhs_V_reg_3648;
wire   [5:0] tmp_108_fu_539_p1;
reg   [5:0] tmp_108_reg_3653;
wire   [0:0] sel_tmp_fu_543_p2;
reg   [0:0] sel_tmp_reg_3658;
wire   [21:0] tmp_s_fu_549_p1;
reg   [21:0] tmp_s_reg_3663;
wire   [21:0] next_mul_fu_553_p2;
reg   [21:0] next_mul_reg_3668;
wire   [0:0] ap_CS_fsm_state2;
wire   [15:0] o_V_fu_563_p2;
reg   [15:0] o_V_reg_3676;
reg   [0:0] tmp_120_reg_3681;
wire   [0:0] exitcond_fu_558_p2;
reg   [9:0] dmem_0_0_V_addr_reg_3688;
reg   [9:0] dmem_0_1_V_addr_reg_3693;
reg   [9:0] dmem_1_0_V_addr_reg_3698;
reg   [9:0] dmem_1_1_V_addr_reg_3703;
wire   [5:0] o_offset_V_fu_628_p2;
reg   [5:0] o_offset_V_reg_3711;
wire   [0:0] ap_CS_fsm_state3;
wire   [63:0] o_word_V_4_fu_667_p3;
reg   [63:0] o_word_V_4_reg_3716;
wire   [0:0] tmp_52_fu_675_p2;
reg   [0:0] tmp_52_reg_3723;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg   [0:0] ap_pipeline_reg_pp0_iter1_tmp_52_reg_3723;
reg   [0:0] ap_pipeline_reg_pp0_iter2_tmp_52_reg_3723;
reg   [0:0] ap_pipeline_reg_pp0_iter3_tmp_52_reg_3723;
reg   [0:0] ap_pipeline_reg_pp0_iter4_tmp_52_reg_3723;
reg   [0:0] ap_pipeline_reg_pp0_iter5_tmp_52_reg_3723;
wire   [15:0] i_V_fu_724_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] r_V_s_fu_737_p2;
reg   [63:0] r_V_s_reg_3762;
reg   [0:0] tmp_123_reg_3767;
reg   [0:0] tmp_124_reg_3772;
reg   [0:0] tmp_125_reg_3777;
reg   [0:0] tmp_126_reg_3782;
reg   [0:0] tmp_127_reg_3787;
reg   [0:0] tmp_128_reg_3792;
reg   [0:0] tmp_129_reg_3797;
reg   [0:0] tmp_145_reg_3802;
reg   [0:0] tmp_171_reg_3807;
reg   [0:0] tmp_175_reg_3812;
reg   [0:0] tmp_176_reg_3817;
reg   [0:0] tmp_177_reg_3822;
reg   [0:0] tmp_178_reg_3827;
reg   [0:0] tmp_179_reg_3832;
reg   [0:0] tmp_180_reg_3837;
reg   [0:0] tmp_181_reg_3842;
reg   [0:0] tmp_182_reg_3847;
reg   [0:0] tmp_183_reg_3852;
reg   [0:0] tmp_184_reg_3857;
reg   [0:0] tmp_185_reg_3862;
reg   [0:0] tmp_186_reg_3867;
reg   [0:0] tmp_187_reg_3872;
reg   [0:0] tmp_188_reg_3877;
reg   [0:0] tmp_189_reg_3882;
reg   [0:0] tmp_190_reg_3887;
reg   [0:0] tmp_191_reg_3892;
reg   [0:0] tmp_192_reg_3897;
reg   [0:0] tmp_193_reg_3902;
reg   [0:0] tmp_194_reg_3907;
reg   [0:0] tmp_195_reg_3912;
reg   [0:0] tmp_196_reg_3917;
reg   [0:0] tmp_197_reg_3922;
wire   [63:0] r_V_49_1_fu_1006_p2;
reg   [63:0] r_V_49_1_reg_3927;
reg   [0:0] tmp_200_reg_3932;
reg   [0:0] tmp_201_reg_3937;
reg   [0:0] tmp_202_reg_3942;
reg   [0:0] tmp_203_reg_3947;
reg   [0:0] tmp_204_reg_3952;
reg   [0:0] tmp_205_reg_3957;
reg   [0:0] tmp_206_reg_3962;
reg   [0:0] tmp_222_reg_3967;
reg   [0:0] tmp_248_reg_3972;
reg   [0:0] tmp_252_reg_3977;
reg   [0:0] tmp_256_reg_3982;
reg   [0:0] tmp_257_reg_3987;
reg   [0:0] tmp_258_reg_3992;
reg   [0:0] tmp_259_reg_3997;
reg   [0:0] tmp_260_reg_4002;
reg   [0:0] tmp_261_reg_4007;
reg   [0:0] tmp_262_reg_4012;
reg   [0:0] tmp_263_reg_4017;
reg   [0:0] tmp_264_reg_4022;
reg   [0:0] tmp_265_reg_4027;
reg   [0:0] tmp_266_reg_4032;
reg   [0:0] tmp_267_reg_4037;
reg   [0:0] tmp_268_reg_4042;
reg   [0:0] tmp_269_reg_4047;
reg   [0:0] tmp_270_reg_4052;
reg   [0:0] tmp_271_reg_4057;
reg   [0:0] tmp_272_reg_4062;
reg   [0:0] tmp_273_reg_4067;
reg   [0:0] tmp_274_reg_4072;
reg   [0:0] tmp_275_reg_4077;
reg   [0:0] tmp_276_reg_4082;
reg   [0:0] tmp_277_reg_4087;
reg   [1:0] tmp_56_reg_4092;
reg   [1:0] tmp_57_reg_4097;
reg   [1:0] tmp_58_reg_4103;
reg   [1:0] tmp_59_reg_4109;
reg   [1:0] tmp_60_reg_4115;
reg   [1:0] tmp_61_reg_4121;
reg   [1:0] tmp_62_reg_4127;
reg   [1:0] tmp_63_reg_4133;
reg   [1:0] tmp_64_reg_4139;
reg   [1:0] tmp_65_reg_4145;
reg   [1:0] tmp_66_reg_4151;
reg   [1:0] tmp_67_reg_4157;
reg   [1:0] tmp_68_reg_4163;
reg   [1:0] tmp_69_reg_4169;
reg   [1:0] tmp_70_reg_4175;
wire   [1:0] tmp_198_fu_1525_p1;
reg   [1:0] tmp_198_reg_4181;
reg   [1:0] tmp_71_reg_4188;
reg   [1:0] tmp_72_reg_4193;
reg   [1:0] tmp_73_reg_4199;
reg   [1:0] tmp_76_reg_4205;
reg   [1:0] tmp_83_reg_4211;
reg   [1:0] tmp_94_reg_4217;
reg   [1:0] tmp_130_reg_4223;
reg   [1:0] tmp_131_reg_4229;
reg   [1:0] tmp_132_reg_4235;
reg   [1:0] tmp_133_reg_4241;
reg   [1:0] tmp_134_reg_4247;
reg   [1:0] tmp_135_reg_4253;
reg   [1:0] tmp_136_reg_4259;
reg   [1:0] tmp_137_reg_4265;
reg   [1:0] tmp_138_reg_4271;
reg   [1:0] tmp_139_reg_4277;
reg   [1:0] tmp_153_reg_4284;
reg   [1:0] tmp_154_reg_4289;
reg   [1:0] tmp_155_reg_4295;
reg   [1:0] tmp_156_reg_4301;
reg   [1:0] tmp_157_reg_4307;
reg   [1:0] tmp_158_reg_4313;
reg   [1:0] tmp_159_reg_4319;
reg   [1:0] tmp_160_reg_4325;
reg   [1:0] tmp_161_reg_4331;
reg   [1:0] tmp_162_reg_4337;
reg   [1:0] tmp_163_reg_4343;
reg   [1:0] tmp_164_reg_4349;
reg   [1:0] tmp_165_reg_4355;
reg   [1:0] tmp_166_reg_4361;
reg   [1:0] tmp_167_reg_4367;
wire   [1:0] tmp_278_fu_1946_p1;
reg   [1:0] tmp_278_reg_4373;
reg   [1:0] tmp_168_reg_4380;
reg   [1:0] tmp_169_reg_4385;
reg   [1:0] tmp_170_reg_4391;
reg   [1:0] tmp_172_reg_4397;
reg   [1:0] tmp_173_reg_4403;
reg   [1:0] tmp_174_reg_4409;
reg   [1:0] tmp_207_reg_4415;
reg   [1:0] tmp_208_reg_4421;
reg   [1:0] tmp_209_reg_4427;
reg   [1:0] tmp_210_reg_4433;
reg   [1:0] tmp_211_reg_4439;
reg   [1:0] tmp_212_reg_4445;
reg   [1:0] tmp_213_reg_4451;
reg   [1:0] tmp_214_reg_4457;
reg   [1:0] tmp_215_reg_4463;
reg   [1:0] tmp_216_reg_4469;
reg   [3:0] tmp_142_reg_4476;
reg   [3:0] tmp_143_reg_4482;
reg   [3:0] tmp_144_reg_4489;
reg   [3:0] tmp_146_reg_4497;
reg   [3:0] tmp_147_reg_4505;
reg   [3:0] tmp_148_reg_4513;
reg   [3:0] tmp_149_reg_4521;
reg   [3:0] ap_pipeline_reg_pp0_iter4_tmp_149_reg_4521;
wire   [3:0] tmp_199_fu_2440_p1;
reg   [3:0] tmp_199_reg_4530;
wire   [3:0] tmp_80_fu_2450_p2;
reg   [3:0] tmp_80_reg_4536;
reg   [3:0] ap_pipeline_reg_pp0_iter4_tmp_80_reg_4536;
reg   [3:0] tmp_219_reg_4541;
reg   [3:0] tmp_220_reg_4547;
reg   [3:0] tmp_221_reg_4554;
reg   [3:0] tmp_223_reg_4562;
reg   [3:0] tmp_224_reg_4570;
reg   [3:0] tmp_225_reg_4578;
reg   [3:0] tmp_226_reg_4586;
reg   [3:0] ap_pipeline_reg_pp0_iter4_tmp_226_reg_4586;
wire   [3:0] tmp_279_fu_2786_p1;
reg   [3:0] tmp_279_reg_4595;
wire   [3:0] tmp_102_fu_2796_p2;
reg   [3:0] tmp_102_reg_4601;
reg   [3:0] ap_pipeline_reg_pp0_iter4_tmp_102_reg_4601;
reg   [6:0] tmp_89_reg_4606;
reg   [6:0] tmp_90_reg_4611;
reg   [6:0] tmp_115_reg_4616;
reg   [6:0] tmp_116_reg_4621;
wire   [6:0] tmp_93_fu_3148_p2;
reg   [6:0] tmp_93_reg_4626;
wire   [6:0] tmp_1703_s_fu_3174_p2;
reg   [6:0] tmp_1703_s_reg_4631;
wire   [15:0] sum_V_1_fu_3232_p2;
reg    ap_enable_reg_pp0_iter6;
wire   [0:0] ap_CS_fsm_state11;
wire   [0:0] kh_off_V_1_fu_3253_p1;
reg   [0:0] kh_off_V_1_reg_4646;
wire   [0:0] ap_CS_fsm_state12;
reg   [63:0] kh_word_V_2_reg_4651;
wire   [15:0] ki_V_2_fu_3271_p3;
reg  signed [15:0] ki_V_2_reg_4657;
wire   [0:0] ap_CS_fsm_state13;
wire   [0:0] ap_CS_fsm_state14;
wire  signed [35:0] grp_fu_3602_p2;
reg  signed [35:0] p_Val2_1_reg_4677;
wire   [36:0] p_Val2_2_fu_3389_p2;
reg   [36:0] p_Val2_2_reg_4682;
wire   [0:0] ap_CS_fsm_state15;
wire   [0:0] not_s_fu_3509_p2;
reg   [0:0] not_s_reg_4687;
wire   [0:0] sel_tmp25_demorgan_fu_3521_p2;
reg   [0:0] sel_tmp25_demorgan_reg_4692;
wire   [15:0] best_out_V_2_fu_3565_p3;
wire   [0:0] ap_CS_fsm_state16;
wire   [7:0] prediction_V_2_fu_3595_p3;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg   [15:0] p_Val2_7_reg_458;
reg   [7:0] p_Val2_s_reg_470;
reg   [15:0] p_s_reg_482;
reg   [21:0] phi_mul_reg_494;
wire   [63:0] tmp_51_fu_593_p1;
wire   [0:0] tmp_48_fu_609_p2;
wire   [63:0] tmp_54_fu_700_p1;
wire   [63:0] tmp_55_fu_718_p1;
wire   [63:0] tmp_87_fu_3248_p1;
wire   [63:0] tmp_84_fu_3308_p1;
wire   [63:0] o_word_V_3_fu_3578_p3;
wire   [63:0] p_Result_9_fu_614_p3;
wire   [16:0] rhs_V_fu_569_p1;
wire   [16:0] r_V_fu_578_p2;
wire   [9:0] tmp_50_fu_583_p4;
wire   [15:0] tmp_43_fu_573_p2;
wire   [5:0] tmp_113_fu_624_p1;
wire   [0:0] sel_tmp1_fu_633_p2;
wire   [0:0] sel_tmp3_fu_645_p2;
wire   [0:0] sel_tmp4_fu_650_p2;
wire   [63:0] sel_tmp2_fu_637_p3;
wire   [0:0] sel_tmp6_fu_663_p2;
wire   [63:0] sel_tmp5_fu_655_p3;
wire   [21:0] rhs_V_4_cast_fu_680_p1;
wire   [8:0] r_V_9_fu_690_p4;
wire   [21:0] r_V_7_fu_684_p2;
wire   [14:0] p_0856_s_fu_708_p4;
wire   [63:0] in_wrd_V_0_phi_fu_730_p3;
wire   [63:0] in_wrd_V_1_phi_fu_999_p3;
wire   [62:0] r_V_1_fu_1268_p64;
wire   [63:0] r_V_1_cast_fu_1366_p1;
wire   [63:0] x_V_6_fu_1370_p2;
wire   [62:0] r_V_44_1_fu_1689_p64;
wire   [63:0] r_V_44_1_cast_fu_1787_p1;
wire   [63:0] x_V_6_1_fu_1791_p2;
wire   [61:0] r_V_2_fu_2110_p32;
wire   [61:0] r_V_3_fu_2164_p32;
wire   [62:0] r_V_2_cast_fu_2160_p1;
wire   [62:0] r_V_3_cast_fu_2214_p1;
wire   [62:0] x_V_fu_2322_p2;
wire   [58:0] tmp_141_fu_2334_p4;
wire   [59:0] tmp_74_fu_2218_p31;
wire   [59:0] tmp_75_fu_2267_p31;
wire   [59:0] tmp_78_fu_2348_p2;
wire   [59:0] tmp_77_fu_2344_p1;
wire   [61:0] tmp_140_fu_2316_p2;
wire   [59:0] tmp_134_cast_fu_2354_p2;
wire   [3:0] tmp_79_fu_2360_p4;
wire   [3:0] tmp_96_cast_fu_2331_p1;
wire   [3:0] tmp_95_cast_fu_2328_p1;
wire   [3:0] tmp41_fu_2444_p2;
wire   [61:0] r_V_45_1_fu_2456_p32;
wire   [61:0] r_V_46_1_fu_2510_p32;
wire   [62:0] r_V_45_1_cast_fu_2506_p1;
wire   [62:0] r_V_46_1_cast_fu_2560_p1;
wire   [62:0] x_V_1_fu_2668_p2;
wire   [58:0] tmp_218_fu_2680_p4;
wire   [59:0] tmp_97_fu_2564_p31;
wire   [59:0] tmp_98_fu_2613_p31;
wire   [59:0] tmp_100_fu_2694_p2;
wire   [59:0] tmp_99_fu_2690_p1;
wire   [61:0] tmp_217_fu_2662_p2;
wire   [59:0] tmp_168_1_cast_fu_2700_p2;
wire   [3:0] tmp_101_fu_2706_p4;
wire   [3:0] tmp_118_cast_fu_2677_p1;
wire   [3:0] tmp_117_cast_fu_2674_p1;
wire   [3:0] tmp44_fu_2790_p2;
wire   [59:0] x_V_2_fu_2802_p16;
wire   [51:0] r_V_4_fu_2832_p14;
wire   [59:0] tmp_150_fu_2855_p1;
wire   [60:0] x_V_2_cast_fu_2828_p1;
wire   [60:0] r_V_4_cast_fu_2859_p1;
wire   [46:0] tmp_81_fu_2863_p13;
wire   [46:0] tmp_82_fu_2885_p13;
wire   [60:0] x_V_3_fu_2913_p2;
wire   [44:0] tmp_152_fu_2925_p4;
wire   [46:0] x_V_3_cast_fu_2919_p2;
wire   [46:0] r_V_5_cast_fu_2935_p1;
wire   [59:0] tmp_151_fu_2907_p2;
wire   [46:0] x_V_4_fu_2939_p2;
wire   [59:0] x_V_2_1_fu_2965_p16;
wire   [51:0] r_V_47_1_fu_2995_p14;
wire   [59:0] tmp_227_fu_3018_p1;
wire   [60:0] x_V_2_1_cast_fu_2991_p1;
wire   [60:0] r_V_47_1_cast_fu_3022_p1;
wire   [46:0] tmp_103_fu_3026_p13;
wire   [46:0] tmp_104_fu_3048_p13;
wire   [60:0] x_V_3_1_fu_3076_p2;
wire   [44:0] tmp_229_fu_3088_p4;
wire   [46:0] x_V_3_1_cast_fu_3082_p2;
wire   [46:0] r_V_48_1_cast_fu_3098_p1;
wire   [59:0] tmp_228_fu_3070_p2;
wire   [46:0] x_V_4_1_fu_3102_p2;
wire   [6:0] tmp_85_fu_3128_p3;
wire   [6:0] tmp_88_fu_3135_p1;
wire   [6:0] tmp_92_fu_3144_p2;
wire   [6:0] tmp_91_fu_3138_p2;
wire   [6:0] tmp_105_fu_3154_p3;
wire   [6:0] tmp_111_fu_3161_p1;
wire   [6:0] tmp_118_fu_3170_p2;
wire   [6:0] tmp_117_fu_3164_p2;
wire   [7:0] tmp_95_fu_3180_p3;
wire   [8:0] phitmp_cast_fu_3187_p1;
wire   [8:0] tmp_96_fu_3191_p2;
wire   [7:0] tmp_171_1_fu_3201_p3;
wire   [8:0] phitmp_1_cast_fu_3208_p1;
wire   [8:0] tmp_172_1_fu_3212_p2;
wire  signed [9:0] tmp_139_cast_fu_3197_p1;
wire  signed [9:0] tmp_172_1_cast_fu_3218_p1;
wire   [9:0] tmp_119_fu_3222_p2;
wire  signed [15:0] p_cast_fu_3228_p1;
wire   [14:0] r_V_11_fu_3238_p4;
wire   [15:0] loc_V_8_fu_3261_p4;
wire   [15:0] loc_V_7_fu_3257_p1;
wire   [9:0] tmp_284_fu_3279_p1;
wire  signed [19:0] tmp_109_fu_3283_p3;
wire   [13:0] r_V_10_fu_3298_p4;
wire   [1:0] kh_off_V_fu_3313_p1;
wire   [15:0] tmp_230_fu_3352_p4;
wire   [15:0] tmp_231_fu_3361_p4;
wire   [15:0] tmp_232_fu_3370_p3;
wire   [27:0] tmp_112_fu_3377_p3;
wire  signed [36:0] tmp_112_cast_fu_3385_p1;
wire   [36:0] tmp_110_fu_3349_p1;
wire   [19:0] p_Val2_6_fu_3395_p4;
wire  signed [21:0] tmp_128_cast_fu_3431_p1;
wire   [21:0] tmp_121_fu_3435_p3;
wire   [0:0] tmp_86_fu_3317_p2;
wire   [0:0] tmp_106_fu_3327_p2;
wire   [0:0] sel_tmp12_fu_3449_p2;
wire   [0:0] sel_tmp17_demorgan_fu_3461_p2;
wire   [0:0] tmp_107_fu_3343_p2;
wire   [0:0] sel_tmp14_fu_3467_p2;
wire   [0:0] sel_tmp15_fu_3473_p2;
wire   [15:0] loc_V_10_fu_3411_p4;
wire   [15:0] loc_V_9_fu_3333_p4;
wire   [0:0] sel_tmp13_fu_3455_p2;
wire   [15:0] loc_V_fu_3323_p1;
wire   [15:0] loc_V_11_fu_3421_p4;
wire   [0:0] or_cond_fu_3487_p2;
wire   [15:0] newSel_fu_3479_p3;
wire   [15:0] newSel1_fu_3493_p3;
wire   [15:0] nc_V_4_fu_3501_p3;
wire   [0:0] tmp_114_fu_3405_p2;
wire   [0:0] tmp_122_fu_3443_p2;
wire   [0:0] tmp47_fu_3515_p2;
wire   [31:0] bvh_d_index_fu_3526_p1;
wire   [63:0] p_Repl2_s_fu_3529_p1;
wire   [13:0] p_Val2_s_51_fu_3545_p4;
wire  signed [15:0] best_out_V_fu_3554_p1;
wire   [15:0] best_out_V_1_fu_3558_p3;
reg   [63:0] p_Result_s_fu_3532_p4;
wire   [63:0] o_word_V_2_fu_3572_p3;
wire   [7:0] prediction_V_fu_3541_p1;
wire   [7:0] prediction_V_1_fu_3588_p3;
reg   [9:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'b1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

top_mul_mul_20s_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 36 ))
top_mul_mul_20s_1bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_109_fu_3283_p3),
    .din1(ki_V_2_reg_4657),
    .ce(1'b1),
    .dout(grp_fu_3602_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == tmp_52_fu_675_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(1'b0 == tmp_52_fu_675_p2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == tmp_52_fu_675_p2)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(1'b0 == tmp_52_fu_675_p2) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        p_5_reg_518 <= i_V_fu_724_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_5_reg_518 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter6) & ~(1'b0 == ap_pipeline_reg_pp0_iter5_tmp_52_reg_3723))) begin
        p_Val2_3_reg_506 <= sum_V_1_fu_3232_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Val2_3_reg_506 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        p_Val2_7_reg_458 <= best_out_V_2_fu_3565_p3;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        p_Val2_7_reg_458 <= ap_const_lv16_C000;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        p_Val2_s_reg_470 <= prediction_V_2_fu_3595_p3;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        p_Val2_s_reg_470 <= ap_const_lv8_FF;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        p_s_reg_482 <= o_V_reg_3676;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        p_s_reg_482 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        phi_mul_reg_494 <= next_mul_reg_3668;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        phi_mul_reg_494 <= ap_const_lv22_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_pipeline_reg_pp0_iter1_tmp_52_reg_3723 <= tmp_52_reg_3723;
        tmp_52_reg_3723 <= tmp_52_fu_675_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == 1'b1)) begin
        ap_pipeline_reg_pp0_iter2_tmp_52_reg_3723 <= ap_pipeline_reg_pp0_iter1_tmp_52_reg_3723;
        ap_pipeline_reg_pp0_iter3_tmp_52_reg_3723 <= ap_pipeline_reg_pp0_iter2_tmp_52_reg_3723;
        ap_pipeline_reg_pp0_iter4_tmp_102_reg_4601 <= tmp_102_reg_4601;
        ap_pipeline_reg_pp0_iter4_tmp_149_reg_4521 <= tmp_149_reg_4521;
        ap_pipeline_reg_pp0_iter4_tmp_226_reg_4586 <= tmp_226_reg_4586;
        ap_pipeline_reg_pp0_iter4_tmp_52_reg_3723 <= ap_pipeline_reg_pp0_iter3_tmp_52_reg_3723;
        ap_pipeline_reg_pp0_iter4_tmp_80_reg_4536 <= tmp_80_reg_4536;
        ap_pipeline_reg_pp0_iter5_tmp_52_reg_3723 <= ap_pipeline_reg_pp0_iter4_tmp_52_reg_3723;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_558_p2 == 1'b0))) begin
        dmem_0_0_V_addr_reg_3688 <= tmp_51_fu_593_p1;
        dmem_0_1_V_addr_reg_3693 <= tmp_51_fu_593_p1;
        dmem_1_0_V_addr_reg_3698 <= tmp_51_fu_593_p1;
        dmem_1_1_V_addr_reg_3703 <= tmp_51_fu_593_p1;
        tmp_120_reg_3681 <= tmp_43_fu_573_p2[ap_const_lv32_6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        kh_off_V_1_reg_4646 <= kh_off_V_1_fu_3253_p1;
        kh_word_V_2_reg_4651 <= kh_mem_V_q0;
        ki_V_2_reg_4657 <= ki_V_2_fu_3271_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        lhs_V_reg_3648[15 : 0] <= lhs_V_fu_535_p1[15 : 0];
        sel_tmp_reg_3658 <= sel_tmp_fu_543_p2;
        tmp_108_reg_3653 <= tmp_108_fu_539_p1;
        tmp_reg_3640 <= tmp_fu_529_p2;
        tmp_s_reg_3663[15 : 0] <= tmp_s_fu_549_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        next_mul_reg_3668 <= next_mul_fu_553_p2;
        o_V_reg_3676 <= o_V_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(tmp_reg_3640 == 1'b0) & (1'b1 == ap_CS_fsm_state15))) begin
        not_s_reg_4687 <= not_s_fu_3509_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ~(tmp_reg_3640 == 1'b0))) begin
        o_offset_V_reg_3711 <= o_offset_V_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        o_word_V_4_reg_3716 <= o_word_V_4_fu_667_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_Val2_1_reg_4677 <= grp_fu_3602_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        p_Val2_2_reg_4682 <= p_Val2_2_fu_3389_p2;
        sel_tmp25_demorgan_reg_4692 <= sel_tmp25_demorgan_fu_3521_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(1'b0 == tmp_52_reg_3723))) begin
        r_V_49_1_reg_3927 <= r_V_49_1_fu_1006_p2;
        r_V_s_reg_3762 <= r_V_s_fu_737_p2;
        tmp_123_reg_3767 <= r_V_s_fu_737_p2[ap_const_lv32_3F];
        tmp_124_reg_3772 <= r_V_s_fu_737_p2[ap_const_lv32_3D];
        tmp_125_reg_3777 <= r_V_s_fu_737_p2[ap_const_lv32_3B];
        tmp_126_reg_3782 <= r_V_s_fu_737_p2[ap_const_lv32_39];
        tmp_127_reg_3787 <= r_V_s_fu_737_p2[ap_const_lv32_37];
        tmp_128_reg_3792 <= r_V_s_fu_737_p2[ap_const_lv32_35];
        tmp_129_reg_3797 <= r_V_s_fu_737_p2[ap_const_lv32_33];
        tmp_145_reg_3802 <= r_V_s_fu_737_p2[ap_const_lv32_31];
        tmp_171_reg_3807 <= r_V_s_fu_737_p2[ap_const_lv32_2F];
        tmp_175_reg_3812 <= r_V_s_fu_737_p2[ap_const_lv32_2D];
        tmp_176_reg_3817 <= r_V_s_fu_737_p2[ap_const_lv32_2B];
        tmp_177_reg_3822 <= r_V_s_fu_737_p2[ap_const_lv32_29];
        tmp_178_reg_3827 <= r_V_s_fu_737_p2[ap_const_lv32_27];
        tmp_179_reg_3832 <= r_V_s_fu_737_p2[ap_const_lv32_25];
        tmp_180_reg_3837 <= r_V_s_fu_737_p2[ap_const_lv32_23];
        tmp_181_reg_3842 <= r_V_s_fu_737_p2[ap_const_lv32_21];
        tmp_182_reg_3847 <= r_V_s_fu_737_p2[ap_const_lv32_1F];
        tmp_183_reg_3852 <= r_V_s_fu_737_p2[ap_const_lv32_1D];
        tmp_184_reg_3857 <= r_V_s_fu_737_p2[ap_const_lv32_1B];
        tmp_185_reg_3862 <= r_V_s_fu_737_p2[ap_const_lv32_19];
        tmp_186_reg_3867 <= r_V_s_fu_737_p2[ap_const_lv32_17];
        tmp_187_reg_3872 <= r_V_s_fu_737_p2[ap_const_lv32_15];
        tmp_188_reg_3877 <= r_V_s_fu_737_p2[ap_const_lv32_13];
        tmp_189_reg_3882 <= r_V_s_fu_737_p2[ap_const_lv32_11];
        tmp_190_reg_3887 <= r_V_s_fu_737_p2[ap_const_lv32_F];
        tmp_191_reg_3892 <= r_V_s_fu_737_p2[ap_const_lv32_D];
        tmp_192_reg_3897 <= r_V_s_fu_737_p2[ap_const_lv32_B];
        tmp_193_reg_3902 <= r_V_s_fu_737_p2[ap_const_lv32_9];
        tmp_194_reg_3907 <= r_V_s_fu_737_p2[ap_const_lv32_7];
        tmp_195_reg_3912 <= r_V_s_fu_737_p2[ap_const_lv32_5];
        tmp_196_reg_3917 <= r_V_s_fu_737_p2[ap_const_lv32_3];
        tmp_197_reg_3922 <= r_V_s_fu_737_p2[ap_const_lv32_1];
        tmp_200_reg_3932 <= r_V_49_1_fu_1006_p2[ap_const_lv32_3F];
        tmp_201_reg_3937 <= r_V_49_1_fu_1006_p2[ap_const_lv32_3D];
        tmp_202_reg_3942 <= r_V_49_1_fu_1006_p2[ap_const_lv32_3B];
        tmp_203_reg_3947 <= r_V_49_1_fu_1006_p2[ap_const_lv32_39];
        tmp_204_reg_3952 <= r_V_49_1_fu_1006_p2[ap_const_lv32_37];
        tmp_205_reg_3957 <= r_V_49_1_fu_1006_p2[ap_const_lv32_35];
        tmp_206_reg_3962 <= r_V_49_1_fu_1006_p2[ap_const_lv32_33];
        tmp_222_reg_3967 <= r_V_49_1_fu_1006_p2[ap_const_lv32_31];
        tmp_248_reg_3972 <= r_V_49_1_fu_1006_p2[ap_const_lv32_2F];
        tmp_252_reg_3977 <= r_V_49_1_fu_1006_p2[ap_const_lv32_2D];
        tmp_256_reg_3982 <= r_V_49_1_fu_1006_p2[ap_const_lv32_2B];
        tmp_257_reg_3987 <= r_V_49_1_fu_1006_p2[ap_const_lv32_29];
        tmp_258_reg_3992 <= r_V_49_1_fu_1006_p2[ap_const_lv32_27];
        tmp_259_reg_3997 <= r_V_49_1_fu_1006_p2[ap_const_lv32_25];
        tmp_260_reg_4002 <= r_V_49_1_fu_1006_p2[ap_const_lv32_23];
        tmp_261_reg_4007 <= r_V_49_1_fu_1006_p2[ap_const_lv32_21];
        tmp_262_reg_4012 <= r_V_49_1_fu_1006_p2[ap_const_lv32_1F];
        tmp_263_reg_4017 <= r_V_49_1_fu_1006_p2[ap_const_lv32_1D];
        tmp_264_reg_4022 <= r_V_49_1_fu_1006_p2[ap_const_lv32_1B];
        tmp_265_reg_4027 <= r_V_49_1_fu_1006_p2[ap_const_lv32_19];
        tmp_266_reg_4032 <= r_V_49_1_fu_1006_p2[ap_const_lv32_17];
        tmp_267_reg_4037 <= r_V_49_1_fu_1006_p2[ap_const_lv32_15];
        tmp_268_reg_4042 <= r_V_49_1_fu_1006_p2[ap_const_lv32_13];
        tmp_269_reg_4047 <= r_V_49_1_fu_1006_p2[ap_const_lv32_11];
        tmp_270_reg_4052 <= r_V_49_1_fu_1006_p2[ap_const_lv32_F];
        tmp_271_reg_4057 <= r_V_49_1_fu_1006_p2[ap_const_lv32_D];
        tmp_272_reg_4062 <= r_V_49_1_fu_1006_p2[ap_const_lv32_B];
        tmp_273_reg_4067 <= r_V_49_1_fu_1006_p2[ap_const_lv32_9];
        tmp_274_reg_4072 <= r_V_49_1_fu_1006_p2[ap_const_lv32_7];
        tmp_275_reg_4077 <= r_V_49_1_fu_1006_p2[ap_const_lv32_5];
        tmp_276_reg_4082 <= r_V_49_1_fu_1006_p2[ap_const_lv32_3];
        tmp_277_reg_4087 <= r_V_49_1_fu_1006_p2[ap_const_lv32_1];
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b0 == ap_pipeline_reg_pp0_iter2_tmp_52_reg_3723)) begin
        tmp_102_reg_4601 <= tmp_102_fu_2796_p2;
        tmp_142_reg_4476 <= {{tmp_134_cast_fu_2354_p2[ap_const_lv32_3B : ap_const_lv32_38]}};
        tmp_143_reg_4482 <= {{tmp_134_cast_fu_2354_p2[ap_const_lv32_33 : ap_const_lv32_30]}};
        tmp_144_reg_4489 <= {{tmp_134_cast_fu_2354_p2[ap_const_lv32_2B : ap_const_lv32_28]}};
        tmp_146_reg_4497 <= {{tmp_134_cast_fu_2354_p2[ap_const_lv32_23 : ap_const_lv32_20]}};
        tmp_147_reg_4505 <= {{tmp_134_cast_fu_2354_p2[ap_const_lv32_1B : ap_const_lv32_18]}};
        tmp_148_reg_4513 <= {{tmp_134_cast_fu_2354_p2[ap_const_lv32_13 : ap_const_lv32_10]}};
        tmp_149_reg_4521 <= {{tmp_134_cast_fu_2354_p2[ap_const_lv32_B : ap_const_lv32_8]}};
        tmp_199_reg_4530 <= tmp_199_fu_2440_p1;
        tmp_219_reg_4541 <= {{tmp_168_1_cast_fu_2700_p2[ap_const_lv32_3B : ap_const_lv32_38]}};
        tmp_220_reg_4547 <= {{tmp_168_1_cast_fu_2700_p2[ap_const_lv32_33 : ap_const_lv32_30]}};
        tmp_221_reg_4554 <= {{tmp_168_1_cast_fu_2700_p2[ap_const_lv32_2B : ap_const_lv32_28]}};
        tmp_223_reg_4562 <= {{tmp_168_1_cast_fu_2700_p2[ap_const_lv32_23 : ap_const_lv32_20]}};
        tmp_224_reg_4570 <= {{tmp_168_1_cast_fu_2700_p2[ap_const_lv32_1B : ap_const_lv32_18]}};
        tmp_225_reg_4578 <= {{tmp_168_1_cast_fu_2700_p2[ap_const_lv32_13 : ap_const_lv32_10]}};
        tmp_226_reg_4586 <= {{tmp_168_1_cast_fu_2700_p2[ap_const_lv32_B : ap_const_lv32_8]}};
        tmp_279_reg_4595 <= tmp_279_fu_2786_p1;
        tmp_80_reg_4536 <= tmp_80_fu_2450_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b0 == ap_pipeline_reg_pp0_iter3_tmp_52_reg_3723)) begin
        tmp_115_reg_4616 <= {{tmp_228_fu_3070_p2[ap_const_lv32_16 : ap_const_lv32_10]}};
        tmp_116_reg_4621 <= {{x_V_4_1_fu_3102_p2[ap_const_lv32_26 : ap_const_lv32_20]}};
        tmp_89_reg_4606 <= {{tmp_151_fu_2907_p2[ap_const_lv32_16 : ap_const_lv32_10]}};
        tmp_90_reg_4611 <= {{x_V_4_fu_2939_p2[ap_const_lv32_26 : ap_const_lv32_20]}};
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b0 == ap_pipeline_reg_pp0_iter1_tmp_52_reg_3723)) begin
        tmp_130_reg_4223 <= {{x_V_6_fu_1370_p2[ap_const_lv32_27 : ap_const_lv32_26]}};
        tmp_131_reg_4229 <= {{x_V_6_fu_1370_p2[ap_const_lv32_23 : ap_const_lv32_22]}};
        tmp_132_reg_4235 <= {{x_V_6_fu_1370_p2[ap_const_lv32_1F : ap_const_lv32_1E]}};
        tmp_133_reg_4241 <= {{x_V_6_fu_1370_p2[ap_const_lv32_1B : ap_const_lv32_1A]}};
        tmp_134_reg_4247 <= {{x_V_6_fu_1370_p2[ap_const_lv32_17 : ap_const_lv32_16]}};
        tmp_135_reg_4253 <= {{x_V_6_fu_1370_p2[ap_const_lv32_13 : ap_const_lv32_12]}};
        tmp_136_reg_4259 <= {{x_V_6_fu_1370_p2[ap_const_lv32_F : ap_const_lv32_E]}};
        tmp_137_reg_4265 <= {{x_V_6_fu_1370_p2[ap_const_lv32_B : ap_const_lv32_A]}};
        tmp_138_reg_4271 <= {{x_V_6_fu_1370_p2[ap_const_lv32_7 : ap_const_lv32_6]}};
        tmp_139_reg_4277 <= {{x_V_6_fu_1370_p2[ap_const_lv32_3 : ap_const_lv32_2]}};
        tmp_153_reg_4284 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_3D : ap_const_lv32_3C]}};
        tmp_154_reg_4289 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_39 : ap_const_lv32_38]}};
        tmp_155_reg_4295 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_35 : ap_const_lv32_34]}};
        tmp_156_reg_4301 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_31 : ap_const_lv32_30]}};
        tmp_157_reg_4307 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_2D : ap_const_lv32_2C]}};
        tmp_158_reg_4313 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_29 : ap_const_lv32_28]}};
        tmp_159_reg_4319 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_25 : ap_const_lv32_24]}};
        tmp_160_reg_4325 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_21 : ap_const_lv32_20]}};
        tmp_161_reg_4331 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_1D : ap_const_lv32_1C]}};
        tmp_162_reg_4337 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_19 : ap_const_lv32_18]}};
        tmp_163_reg_4343 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_15 : ap_const_lv32_14]}};
        tmp_164_reg_4349 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_11 : ap_const_lv32_10]}};
        tmp_165_reg_4355 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_D : ap_const_lv32_C]}};
        tmp_166_reg_4361 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_9 : ap_const_lv32_8]}};
        tmp_167_reg_4367 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_5 : ap_const_lv32_4]}};
        tmp_168_reg_4380 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_3F : ap_const_lv32_3E]}};
        tmp_169_reg_4385 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_3B : ap_const_lv32_3A]}};
        tmp_170_reg_4391 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_37 : ap_const_lv32_36]}};
        tmp_172_reg_4397 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_33 : ap_const_lv32_32]}};
        tmp_173_reg_4403 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_2F : ap_const_lv32_2E]}};
        tmp_174_reg_4409 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_2B : ap_const_lv32_2A]}};
        tmp_198_reg_4181 <= tmp_198_fu_1525_p1;
        tmp_207_reg_4415 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_27 : ap_const_lv32_26]}};
        tmp_208_reg_4421 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_23 : ap_const_lv32_22]}};
        tmp_209_reg_4427 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_1F : ap_const_lv32_1E]}};
        tmp_210_reg_4433 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_1B : ap_const_lv32_1A]}};
        tmp_211_reg_4439 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_17 : ap_const_lv32_16]}};
        tmp_212_reg_4445 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_13 : ap_const_lv32_12]}};
        tmp_213_reg_4451 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_F : ap_const_lv32_E]}};
        tmp_214_reg_4457 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_B : ap_const_lv32_A]}};
        tmp_215_reg_4463 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_7 : ap_const_lv32_6]}};
        tmp_216_reg_4469 <= {{x_V_6_1_fu_1791_p2[ap_const_lv32_3 : ap_const_lv32_2]}};
        tmp_278_reg_4373 <= tmp_278_fu_1946_p1;
        tmp_56_reg_4092 <= {{x_V_6_fu_1370_p2[ap_const_lv32_3D : ap_const_lv32_3C]}};
        tmp_57_reg_4097 <= {{x_V_6_fu_1370_p2[ap_const_lv32_39 : ap_const_lv32_38]}};
        tmp_58_reg_4103 <= {{x_V_6_fu_1370_p2[ap_const_lv32_35 : ap_const_lv32_34]}};
        tmp_59_reg_4109 <= {{x_V_6_fu_1370_p2[ap_const_lv32_31 : ap_const_lv32_30]}};
        tmp_60_reg_4115 <= {{x_V_6_fu_1370_p2[ap_const_lv32_2D : ap_const_lv32_2C]}};
        tmp_61_reg_4121 <= {{x_V_6_fu_1370_p2[ap_const_lv32_29 : ap_const_lv32_28]}};
        tmp_62_reg_4127 <= {{x_V_6_fu_1370_p2[ap_const_lv32_25 : ap_const_lv32_24]}};
        tmp_63_reg_4133 <= {{x_V_6_fu_1370_p2[ap_const_lv32_21 : ap_const_lv32_20]}};
        tmp_64_reg_4139 <= {{x_V_6_fu_1370_p2[ap_const_lv32_1D : ap_const_lv32_1C]}};
        tmp_65_reg_4145 <= {{x_V_6_fu_1370_p2[ap_const_lv32_19 : ap_const_lv32_18]}};
        tmp_66_reg_4151 <= {{x_V_6_fu_1370_p2[ap_const_lv32_15 : ap_const_lv32_14]}};
        tmp_67_reg_4157 <= {{x_V_6_fu_1370_p2[ap_const_lv32_11 : ap_const_lv32_10]}};
        tmp_68_reg_4163 <= {{x_V_6_fu_1370_p2[ap_const_lv32_D : ap_const_lv32_C]}};
        tmp_69_reg_4169 <= {{x_V_6_fu_1370_p2[ap_const_lv32_9 : ap_const_lv32_8]}};
        tmp_70_reg_4175 <= {{x_V_6_fu_1370_p2[ap_const_lv32_5 : ap_const_lv32_4]}};
        tmp_71_reg_4188 <= {{x_V_6_fu_1370_p2[ap_const_lv32_3F : ap_const_lv32_3E]}};
        tmp_72_reg_4193 <= {{x_V_6_fu_1370_p2[ap_const_lv32_3B : ap_const_lv32_3A]}};
        tmp_73_reg_4199 <= {{x_V_6_fu_1370_p2[ap_const_lv32_37 : ap_const_lv32_36]}};
        tmp_76_reg_4205 <= {{x_V_6_fu_1370_p2[ap_const_lv32_33 : ap_const_lv32_32]}};
        tmp_83_reg_4211 <= {{x_V_6_fu_1370_p2[ap_const_lv32_2F : ap_const_lv32_2E]}};
        tmp_94_reg_4217 <= {{x_V_6_fu_1370_p2[ap_const_lv32_2B : ap_const_lv32_2A]}};
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b0 == ap_pipeline_reg_pp0_iter4_tmp_52_reg_3723)) begin
        tmp_1703_s_reg_4631 <= tmp_1703_s_fu_3174_p2;
        tmp_93_reg_4626 <= tmp_93_fu_3148_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dmem_0_0_V_address0 = dmem_0_0_V_addr_reg_3688;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        dmem_0_0_V_address0 = tmp_54_fu_700_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & (d_o_idx_V_read_read_fu_298_p2 == 1'b0))) begin
        dmem_0_0_V_address0 = ap_const_lv64_0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_558_p2 == 1'b0))) begin
        dmem_0_0_V_address0 = tmp_51_fu_593_p1;
    end else begin
        dmem_0_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_558_p2 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0)) | (1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & (d_o_idx_V_read_read_fu_298_p2 == 1'b0)))) begin
        dmem_0_0_V_ce0 = 1'b1;
    end else begin
        dmem_0_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dmem_0_0_V_d0 = o_word_V_3_fu_3578_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & (d_o_idx_V_read_read_fu_298_p2 == 1'b0))) begin
        dmem_0_0_V_d0 = p_Result_9_fu_614_p3;
    end else begin
        dmem_0_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & (d_o_idx_V_read_read_fu_298_p2 == 1'b0)) | ((1'b1 == ap_CS_fsm_state16) & (d_o_idx_V_read_read_fu_298_p2 == 1'b0) & (tmp_120_reg_3681 == 1'b0)))) begin
        dmem_0_0_V_we0 = 1'b1;
    end else begin
        dmem_0_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dmem_0_1_V_address0 = dmem_0_1_V_addr_reg_3693;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        dmem_0_1_V_address0 = tmp_54_fu_700_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dmem_0_1_V_address0 = tmp_51_fu_593_p1;
    end else begin
        dmem_0_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0)) | (1'b1 == ap_CS_fsm_state16))) begin
        dmem_0_1_V_ce0 = 1'b1;
    end else begin
        dmem_0_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (d_o_idx_V_read_read_fu_298_p2 == 1'b0) & ~(tmp_120_reg_3681 == 1'b0))) begin
        dmem_0_1_V_we0 = 1'b1;
    end else begin
        dmem_0_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dmem_1_0_V_address0 = dmem_1_0_V_addr_reg_3698;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        dmem_1_0_V_address0 = tmp_54_fu_700_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & ~(d_o_idx_V_read_read_fu_298_p2 == 1'b0))) begin
        dmem_1_0_V_address0 = ap_const_lv64_0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_558_p2 == 1'b0))) begin
        dmem_1_0_V_address0 = tmp_51_fu_593_p1;
    end else begin
        dmem_1_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_558_p2 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0)) | (1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & ~(d_o_idx_V_read_read_fu_298_p2 == 1'b0)))) begin
        dmem_1_0_V_ce0 = 1'b1;
    end else begin
        dmem_1_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dmem_1_0_V_d0 = o_word_V_3_fu_3578_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & ~(d_o_idx_V_read_read_fu_298_p2 == 1'b0))) begin
        dmem_1_0_V_d0 = p_Result_9_fu_614_p3;
    end else begin
        dmem_1_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & ~(exitcond_fu_558_p2 == 1'b0) & ~(1'b0 == tmp_48_fu_609_p2) & ~(d_o_idx_V_read_read_fu_298_p2 == 1'b0)) | ((1'b1 == ap_CS_fsm_state16) & ~(d_o_idx_V_read_read_fu_298_p2 == 1'b0) & (tmp_120_reg_3681 == 1'b0)))) begin
        dmem_1_0_V_we0 = 1'b1;
    end else begin
        dmem_1_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dmem_1_1_V_address0 = dmem_1_1_V_addr_reg_3703;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        dmem_1_1_V_address0 = tmp_54_fu_700_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dmem_1_1_V_address0 = tmp_51_fu_593_p1;
    end else begin
        dmem_1_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0)) | (1'b1 == ap_CS_fsm_state16))) begin
        dmem_1_1_V_ce0 = 1'b1;
    end else begin
        dmem_1_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & ~(d_o_idx_V_read_read_fu_298_p2 == 1'b0) & ~(tmp_120_reg_3681 == 1'b0))) begin
        dmem_1_1_V_we0 = 1'b1;
    end else begin
        dmem_1_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        kh_mem_V_address0 = tmp_84_fu_3308_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        kh_mem_V_address0 = tmp_87_fu_3248_p1;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state14))) begin
        kh_mem_V_ce0 = 1'b1;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        wt_mem_0_V_ce0 = 1'b1;
    end else begin
        wt_mem_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        wt_mem_1_V_ce0 = 1'b1;
    end else begin
        wt_mem_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (~(exitcond_fu_558_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter6) & ~(1'b1 == ap_enable_reg_pp0_iter5)) & ~((1'b0 == tmp_52_fu_675_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == tmp_52_fu_675_p2) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'b1 == ap_enable_reg_pp0_iter1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state11 = ap_CS_fsm[ap_const_lv32_4];

assign ap_CS_fsm_state12 = ap_CS_fsm[ap_const_lv32_5];

assign ap_CS_fsm_state13 = ap_CS_fsm[ap_const_lv32_6];

assign ap_CS_fsm_state14 = ap_CS_fsm[ap_const_lv32_7];

assign ap_CS_fsm_state15 = ap_CS_fsm[ap_const_lv32_8];

assign ap_CS_fsm_state16 = ap_CS_fsm[ap_const_lv32_9];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state3 = ap_CS_fsm[ap_const_lv32_2];

assign best_out_V_1_fu_3558_p3 = ((tmp_reg_3640[0:0] === 1'b1) ? p_Val2_7_reg_458 : best_out_V_fu_3554_p1);

assign best_out_V_2_fu_3565_p3 = ((sel_tmp25_demorgan_reg_4692[0:0] === 1'b1) ? best_out_V_1_fu_3558_p3 : p_Val2_7_reg_458);

assign best_out_V_fu_3554_p1 = $signed(p_Val2_s_51_fu_3545_p4);

assign bvh_d_index_fu_3526_p1 = o_offset_V_reg_3711;

assign d_o_idx_V_read_read_fu_298_p2 = d_o_idx_V;

assign dmem_0_1_V_d0 = o_word_V_3_fu_3578_p3;

assign dmem_1_1_V_d0 = o_word_V_3_fu_3578_p3;

assign exitcond_fu_558_p2 = ((p_s_reg_482 == n_outputs) ? 1'b1 : 1'b0);

assign i_V_fu_724_p2 = (ap_const_lv16_80 + p_5_reg_518);

assign in_wrd_V_0_phi_fu_730_p3 = ((d_i_idx_V[0:0] === 1'b1) ? dmem_1_0_V_q0 : dmem_0_0_V_q0);

assign in_wrd_V_1_phi_fu_999_p3 = ((d_i_idx_V[0:0] === 1'b1) ? dmem_1_1_V_q0 : dmem_0_1_V_q0);

assign kh_off_V_1_fu_3253_p1 = p_s_reg_482[0:0];

assign kh_off_V_fu_3313_p1 = p_s_reg_482[1:0];

assign ki_V_2_fu_3271_p3 = ((kh_off_V_1_fu_3253_p1[0:0] === 1'b1) ? loc_V_8_fu_3261_p4 : loc_V_7_fu_3257_p1);

assign lhs_V_fu_535_p1 = o_index_V;

assign loc_V_10_fu_3411_p4 = {{kh_mem_V_q0[ap_const_lv32_2F : ap_const_lv32_20]}};

assign loc_V_11_fu_3421_p4 = {{kh_mem_V_q0[ap_const_lv32_3F : ap_const_lv32_30]}};

assign loc_V_7_fu_3257_p1 = kh_mem_V_q0[15:0];

assign loc_V_8_fu_3261_p4 = {{kh_mem_V_q0[ap_const_lv32_2F : ap_const_lv32_20]}};

assign loc_V_9_fu_3333_p4 = {{kh_mem_V_q0[ap_const_lv32_1F : ap_const_lv32_10]}};

assign loc_V_fu_3323_p1 = kh_mem_V_q0[15:0];

assign nc_V_4_fu_3501_p3 = ((or_cond_fu_3487_p2[0:0] === 1'b1) ? newSel_fu_3479_p3 : newSel1_fu_3493_p3);

assign newSel1_fu_3493_p3 = ((tmp_86_fu_3317_p2[0:0] === 1'b1) ? loc_V_fu_3323_p1 : loc_V_11_fu_3421_p4);

assign newSel_fu_3479_p3 = ((sel_tmp15_fu_3473_p2[0:0] === 1'b1) ? loc_V_10_fu_3411_p4 : loc_V_9_fu_3333_p4);

assign next_mul_fu_553_p2 = (phi_mul_reg_494 + tmp_s_reg_3663);

assign not_s_fu_3509_p2 = (($signed(p_Val2_3_reg_506) < $signed(nc_V_4_fu_3501_p3)) ? 1'b1 : 1'b0);

assign o_V_fu_563_p2 = (p_s_reg_482 + ap_const_lv16_1);

assign o_offset_V_fu_628_p2 = (tmp_113_fu_624_p1 + tmp_108_reg_3653);

assign o_word_V_2_fu_3572_p3 = ((tmp_reg_3640[0:0] === 1'b1) ? p_Result_s_fu_3532_p4 : o_word_V_4_reg_3716);

assign o_word_V_3_fu_3578_p3 = ((sel_tmp25_demorgan_reg_4692[0:0] === 1'b1) ? o_word_V_2_fu_3572_p3 : o_word_V_4_reg_3716);

assign o_word_V_4_fu_667_p3 = ((sel_tmp6_fu_663_p2[0:0] === 1'b1) ? dmem_1_1_V_q0 : sel_tmp5_fu_655_p3);

assign or_cond_fu_3487_p2 = (sel_tmp15_fu_3473_p2 | sel_tmp13_fu_3455_p2);

assign p_0856_s_fu_708_p4 = {{r_V_7_fu_684_p2[ap_const_lv32_15 : ap_const_lv32_7]}};

assign p_Repl2_s_fu_3529_p1 = not_s_reg_4687;

assign p_Result_9_fu_614_p3 = {{ap_const_lv56_0}, {p_Val2_s_reg_470}};

always @ (*) begin
    p_Result_s_fu_3532_p4 = o_word_V_4_reg_3716;
    p_Result_s_fu_3532_p4[bvh_d_index_fu_3526_p1] = |(p_Repl2_s_fu_3529_p1);
end

assign p_Val2_2_fu_3389_p2 = ($signed(tmp_112_cast_fu_3385_p1) + $signed(tmp_110_fu_3349_p1));

assign p_Val2_6_fu_3395_p4 = {{p_Val2_2_fu_3389_p2[ap_const_lv32_21 : ap_const_lv32_E]}};

assign p_Val2_s_51_fu_3545_p4 = {{p_Val2_2_reg_4682[ap_const_lv32_21 : ap_const_lv32_14]}};

assign p_cast_fu_3228_p1 = $signed(tmp_119_fu_3222_p2);

assign phitmp_1_cast_fu_3208_p1 = tmp_171_1_fu_3201_p3;

assign phitmp_cast_fu_3187_p1 = tmp_95_fu_3180_p3;

assign prediction_V_1_fu_3588_p3 = ((tmp_reg_3640[0:0] === 1'b1) ? p_Val2_s_reg_470 : prediction_V_fu_3541_p1);

assign prediction_V_2_fu_3595_p3 = ((sel_tmp25_demorgan_reg_4692[0:0] === 1'b1) ? prediction_V_1_fu_3588_p3 : p_Val2_s_reg_470);

assign prediction_V_fu_3541_p1 = p_s_reg_482[7:0];

assign r_V_10_fu_3298_p4 = {{p_s_reg_482[ap_const_lv32_F : ap_const_lv32_2]}};

assign r_V_11_fu_3238_p4 = {{p_s_reg_482[ap_const_lv32_F : ap_const_lv32_1]}};

assign r_V_1_cast_fu_1366_p1 = r_V_1_fu_1268_p64;

assign r_V_1_fu_1268_p64 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_123_reg_3767}, {1'b0}}, {tmp_124_reg_3772}}, {1'b0}}, {tmp_125_reg_3777}}, {1'b0}}, {tmp_126_reg_3782}}, {1'b0}}, {tmp_127_reg_3787}}, {1'b0}}, {tmp_128_reg_3792}}, {1'b0}}, {tmp_129_reg_3797}}, {1'b0}}, {tmp_145_reg_3802}}, {1'b0}}, {tmp_171_reg_3807}}, {1'b0}}, {tmp_175_reg_3812}}, {1'b0}}, {tmp_176_reg_3817}}, {1'b0}}, {tmp_177_reg_3822}}, {1'b0}}, {tmp_178_reg_3827}}, {1'b0}}, {tmp_179_reg_3832}}, {1'b0}}, {tmp_180_reg_3837}}, {1'b0}}, {tmp_181_reg_3842}}, {1'b0}}, {tmp_182_reg_3847}}, {1'b0}}, {tmp_183_reg_3852}}, {1'b0}}, {tmp_184_reg_3857}}, {1'b0}}, {tmp_185_reg_3862}}, {1'b0}}, {tmp_186_reg_3867}}, {1'b0}}, {tmp_187_reg_3872}}, {1'b0}}, {tmp_188_reg_3877}}, {1'b0}}, {tmp_189_reg_3882}}, {1'b0}}, {tmp_190_reg_3887}}, {1'b0}}, {tmp_191_reg_3892}}, {1'b0}}, {tmp_192_reg_3897}}, {1'b0}}, {tmp_193_reg_3902}}, {1'b0}}, {tmp_194_reg_3907}}, {1'b0}}, {tmp_195_reg_3912}}, {1'b0}}, {tmp_196_reg_3917}}, {1'b0}}, {tmp_197_reg_3922}};

assign r_V_2_cast_fu_2160_p1 = r_V_2_fu_2110_p32;

assign r_V_2_fu_2110_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_56_reg_4092}, {ap_const_lv2_0}}, {tmp_57_reg_4097}}, {ap_const_lv2_0}}, {tmp_58_reg_4103}}, {ap_const_lv2_0}}, {tmp_59_reg_4109}}, {ap_const_lv2_0}}, {tmp_60_reg_4115}}, {ap_const_lv2_0}}, {tmp_61_reg_4121}}, {ap_const_lv2_0}}, {tmp_62_reg_4127}}, {ap_const_lv2_0}}, {tmp_63_reg_4133}}, {ap_const_lv2_0}}, {tmp_64_reg_4139}}, {ap_const_lv2_0}}, {tmp_65_reg_4145}}, {ap_const_lv2_0}}, {tmp_66_reg_4151}}, {ap_const_lv2_0}}, {tmp_67_reg_4157}}, {ap_const_lv2_0}}, {tmp_68_reg_4163}}, {ap_const_lv2_0}}, {tmp_69_reg_4169}}, {ap_const_lv2_0}}, {tmp_70_reg_4175}}, {ap_const_lv2_0}}, {tmp_198_reg_4181}};

assign r_V_3_cast_fu_2214_p1 = r_V_3_fu_2164_p32;

assign r_V_3_fu_2164_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_71_reg_4188}, {ap_const_lv2_0}}, {tmp_72_reg_4193}}, {ap_const_lv2_0}}, {tmp_73_reg_4199}}, {ap_const_lv2_0}}, {tmp_76_reg_4205}}, {ap_const_lv2_0}}, {tmp_83_reg_4211}}, {ap_const_lv2_0}}, {tmp_94_reg_4217}}, {ap_const_lv2_0}}, {tmp_130_reg_4223}}, {ap_const_lv2_0}}, {tmp_131_reg_4229}}, {ap_const_lv2_0}}, {tmp_132_reg_4235}}, {ap_const_lv2_0}}, {tmp_133_reg_4241}}, {ap_const_lv2_0}}, {tmp_134_reg_4247}}, {ap_const_lv2_0}}, {tmp_135_reg_4253}}, {ap_const_lv2_0}}, {tmp_136_reg_4259}}, {ap_const_lv2_0}}, {tmp_137_reg_4265}}, {ap_const_lv2_0}}, {tmp_138_reg_4271}}, {ap_const_lv2_0}}, {tmp_139_reg_4277}};

assign r_V_44_1_cast_fu_1787_p1 = r_V_44_1_fu_1689_p64;

assign r_V_44_1_fu_1689_p64 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_200_reg_3932}, {1'b0}}, {tmp_201_reg_3937}}, {1'b0}}, {tmp_202_reg_3942}}, {1'b0}}, {tmp_203_reg_3947}}, {1'b0}}, {tmp_204_reg_3952}}, {1'b0}}, {tmp_205_reg_3957}}, {1'b0}}, {tmp_206_reg_3962}}, {1'b0}}, {tmp_222_reg_3967}}, {1'b0}}, {tmp_248_reg_3972}}, {1'b0}}, {tmp_252_reg_3977}}, {1'b0}}, {tmp_256_reg_3982}}, {1'b0}}, {tmp_257_reg_3987}}, {1'b0}}, {tmp_258_reg_3992}}, {1'b0}}, {tmp_259_reg_3997}}, {1'b0}}, {tmp_260_reg_4002}}, {1'b0}}, {tmp_261_reg_4007}}, {1'b0}}, {tmp_262_reg_4012}}, {1'b0}}, {tmp_263_reg_4017}}, {1'b0}}, {tmp_264_reg_4022}}, {1'b0}}, {tmp_265_reg_4027}}, {1'b0}}, {tmp_266_reg_4032}}, {1'b0}}, {tmp_267_reg_4037}}, {1'b0}}, {tmp_268_reg_4042}}, {1'b0}}, {tmp_269_reg_4047}}, {1'b0}}, {tmp_270_reg_4052}}, {1'b0}}, {tmp_271_reg_4057}}, {1'b0}}, {tmp_272_reg_4062}}, {1'b0}}, {tmp_273_reg_4067}}, {1'b0}}, {tmp_274_reg_4072}}, {1'b0}}, {tmp_275_reg_4077}}, {1'b0}}, {tmp_276_reg_4082}}, {1'b0}}, {tmp_277_reg_4087}};

assign r_V_45_1_cast_fu_2506_p1 = r_V_45_1_fu_2456_p32;

assign r_V_45_1_fu_2456_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_153_reg_4284}, {ap_const_lv2_0}}, {tmp_154_reg_4289}}, {ap_const_lv2_0}}, {tmp_155_reg_4295}}, {ap_const_lv2_0}}, {tmp_156_reg_4301}}, {ap_const_lv2_0}}, {tmp_157_reg_4307}}, {ap_const_lv2_0}}, {tmp_158_reg_4313}}, {ap_const_lv2_0}}, {tmp_159_reg_4319}}, {ap_const_lv2_0}}, {tmp_160_reg_4325}}, {ap_const_lv2_0}}, {tmp_161_reg_4331}}, {ap_const_lv2_0}}, {tmp_162_reg_4337}}, {ap_const_lv2_0}}, {tmp_163_reg_4343}}, {ap_const_lv2_0}}, {tmp_164_reg_4349}}, {ap_const_lv2_0}}, {tmp_165_reg_4355}}, {ap_const_lv2_0}}, {tmp_166_reg_4361}}, {ap_const_lv2_0}}, {tmp_167_reg_4367}}, {ap_const_lv2_0}}, {tmp_278_reg_4373}};

assign r_V_46_1_cast_fu_2560_p1 = r_V_46_1_fu_2510_p32;

assign r_V_46_1_fu_2510_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{tmp_168_reg_4380}, {ap_const_lv2_0}}, {tmp_169_reg_4385}}, {ap_const_lv2_0}}, {tmp_170_reg_4391}}, {ap_const_lv2_0}}, {tmp_172_reg_4397}}, {ap_const_lv2_0}}, {tmp_173_reg_4403}}, {ap_const_lv2_0}}, {tmp_174_reg_4409}}, {ap_const_lv2_0}}, {tmp_207_reg_4415}}, {ap_const_lv2_0}}, {tmp_208_reg_4421}}, {ap_const_lv2_0}}, {tmp_209_reg_4427}}, {ap_const_lv2_0}}, {tmp_210_reg_4433}}, {ap_const_lv2_0}}, {tmp_211_reg_4439}}, {ap_const_lv2_0}}, {tmp_212_reg_4445}}, {ap_const_lv2_0}}, {tmp_213_reg_4451}}, {ap_const_lv2_0}}, {tmp_214_reg_4457}}, {ap_const_lv2_0}}, {tmp_215_reg_4463}}, {ap_const_lv2_0}}, {tmp_216_reg_4469}};

assign r_V_47_1_cast_fu_3022_p1 = r_V_47_1_fu_2995_p14;

assign r_V_47_1_fu_2995_p14 = {{{{{{{{{{{{{tmp_219_reg_4541}, {ap_const_lv4_0}}, {tmp_220_reg_4547}}, {ap_const_lv4_0}}, {tmp_221_reg_4554}}, {ap_const_lv4_0}}, {tmp_223_reg_4562}}, {ap_const_lv4_0}}, {tmp_224_reg_4570}}, {ap_const_lv4_0}}, {tmp_225_reg_4578}}, {ap_const_lv4_0}}, {tmp_226_reg_4586}};

assign r_V_48_1_cast_fu_3098_p1 = tmp_229_fu_3088_p4;

assign r_V_49_1_fu_1006_p2 = (wt_mem_1_V_q0 ^ in_wrd_V_1_phi_fu_999_p3);

assign r_V_4_cast_fu_2859_p1 = r_V_4_fu_2832_p14;

assign r_V_4_fu_2832_p14 = {{{{{{{{{{{{{tmp_142_reg_4476}, {ap_const_lv4_0}}, {tmp_143_reg_4482}}, {ap_const_lv4_0}}, {tmp_144_reg_4489}}, {ap_const_lv4_0}}, {tmp_146_reg_4497}}, {ap_const_lv4_0}}, {tmp_147_reg_4505}}, {ap_const_lv4_0}}, {tmp_148_reg_4513}}, {ap_const_lv4_0}}, {tmp_149_reg_4521}};

assign r_V_5_cast_fu_2935_p1 = tmp_152_fu_2925_p4;

assign r_V_7_fu_684_p2 = (rhs_V_4_cast_fu_680_p1 + phi_mul_reg_494);

assign r_V_9_fu_690_p4 = {{p_5_reg_518[ap_const_lv32_F : ap_const_lv32_7]}};

assign r_V_fu_578_p2 = (rhs_V_fu_569_p1 + lhs_V_reg_3648);

assign r_V_s_fu_737_p2 = (wt_mem_0_V_q0 ^ in_wrd_V_0_phi_fu_730_p3);

assign rhs_V_4_cast_fu_680_p1 = p_5_reg_518;

assign rhs_V_fu_569_p1 = p_s_reg_482;

assign sel_tmp12_fu_3449_p2 = (tmp_86_fu_3317_p2 ^ 1'b1);

assign sel_tmp13_fu_3455_p2 = (tmp_106_fu_3327_p2 & sel_tmp12_fu_3449_p2);

assign sel_tmp14_fu_3467_p2 = (sel_tmp17_demorgan_fu_3461_p2 ^ 1'b1);

assign sel_tmp15_fu_3473_p2 = (tmp_107_fu_3343_p2 & sel_tmp14_fu_3467_p2);

assign sel_tmp17_demorgan_fu_3461_p2 = (tmp_86_fu_3317_p2 | tmp_106_fu_3327_p2);

assign sel_tmp1_fu_633_p2 = (tmp_120_reg_3681 & sel_tmp_reg_3658);

assign sel_tmp25_demorgan_fu_3521_p2 = (tmp47_fu_3515_p2 | tmp_reg_3640);

assign sel_tmp2_fu_637_p3 = ((sel_tmp1_fu_633_p2[0:0] === 1'b1) ? dmem_0_1_V_q0 : dmem_0_0_V_q0);

assign sel_tmp3_fu_645_p2 = (tmp_120_reg_3681 ^ 1'b1);

assign sel_tmp4_fu_650_p2 = (d_o_idx_V & sel_tmp3_fu_645_p2);

assign sel_tmp5_fu_655_p3 = ((sel_tmp4_fu_650_p2[0:0] === 1'b1) ? dmem_1_0_V_q0 : sel_tmp2_fu_637_p3);

assign sel_tmp6_fu_663_p2 = (tmp_120_reg_3681 & d_o_idx_V);

assign sel_tmp_fu_543_p2 = (d_o_idx_V ^ 1'b1);

assign sum_V_1_fu_3232_p2 = ($signed(p_cast_fu_3228_p1) + $signed(p_Val2_3_reg_506));

assign tmp41_fu_2444_p2 = (tmp_79_fu_2360_p4 + tmp_96_cast_fu_2331_p1);

assign tmp44_fu_2790_p2 = (tmp_101_fu_2706_p4 + tmp_118_cast_fu_2677_p1);

assign tmp47_fu_3515_p2 = (tmp_114_fu_3405_p2 | tmp_122_fu_3443_p2);

assign tmp_100_fu_2694_p2 = (tmp_97_fu_2564_p31 + tmp_98_fu_2613_p31);

assign tmp_101_fu_2706_p4 = {{tmp_217_fu_2662_p2[ap_const_lv32_7 : ap_const_lv32_4]}};

assign tmp_102_fu_2796_p2 = (tmp_117_cast_fu_2674_p1 + tmp44_fu_2790_p2);

assign tmp_103_fu_3026_p13 = {{{{{{{{{{{{{{{{{{{{{{ap_const_lv3_0}, {tmp_220_reg_4547}}}, {ap_const_lv4_0}}}, {tmp_221_reg_4554}}}, {ap_const_lv4_0}}}, {tmp_223_reg_4562}}}, {ap_const_lv4_0}}}, {tmp_224_reg_4570}}}, {ap_const_lv4_0}}}, {tmp_225_reg_4578}}}, {ap_const_lv4_0}}}, {tmp_226_reg_4586}};

assign tmp_104_fu_3048_p13 = {{{{{{{{{{{{{{{{{{{{{{ap_const_lv3_0}, {tmp_221_reg_4554}}}, {ap_const_lv4_0}}}, {tmp_223_reg_4562}}}, {ap_const_lv4_0}}}, {tmp_224_reg_4570}}}, {ap_const_lv4_0}}}, {tmp_225_reg_4578}}}, {ap_const_lv4_0}}}, {tmp_226_reg_4586}}}, {ap_const_lv4_0}}}, {tmp_279_reg_4595}};

assign tmp_105_fu_3154_p3 = {{ap_const_lv3_0}, {ap_pipeline_reg_pp0_iter4_tmp_226_reg_4586}};

assign tmp_106_fu_3327_p2 = ((kh_off_V_fu_3313_p1 == ap_const_lv2_1) ? 1'b1 : 1'b0);

assign tmp_107_fu_3343_p2 = ((kh_off_V_fu_3313_p1 == ap_const_lv2_2) ? 1'b1 : 1'b0);

assign tmp_108_fu_539_p1 = o_index_V[5:0];

assign tmp_109_fu_3283_p3 = {{tmp_284_fu_3279_p1}, {ap_const_lv10_0}};

assign tmp_110_fu_3349_p1 = $unsigned(p_Val2_1_reg_4677);

assign tmp_111_fu_3161_p1 = ap_pipeline_reg_pp0_iter4_tmp_102_reg_4601;

assign tmp_112_cast_fu_3385_p1 = $signed(tmp_112_fu_3377_p3);

assign tmp_112_fu_3377_p3 = {{tmp_232_fu_3370_p3}, {ap_const_lv12_0}};

assign tmp_113_fu_624_p1 = p_s_reg_482[5:0];

assign tmp_114_fu_3405_p2 = ((p_s_reg_482 == ap_const_lv16_0) ? 1'b1 : 1'b0);

assign tmp_117_cast_fu_2674_p1 = tmp_216_reg_4469;

assign tmp_117_fu_3164_p2 = (tmp_105_fu_3154_p3 + tmp_111_fu_3161_p1);

assign tmp_118_cast_fu_2677_p1 = tmp_278_reg_4373;

assign tmp_118_fu_3170_p2 = (tmp_115_reg_4616 + tmp_116_reg_4621);

assign tmp_119_fu_3222_p2 = ($signed(tmp_139_cast_fu_3197_p1) + $signed(tmp_172_1_cast_fu_3218_p1));

assign tmp_121_fu_3435_p3 = {{p_Val2_7_reg_458}, {ap_const_lv6_0}};

assign tmp_122_fu_3443_p2 = (($signed(tmp_128_cast_fu_3431_p1) > $signed(tmp_121_fu_3435_p3)) ? 1'b1 : 1'b0);

assign tmp_128_cast_fu_3431_p1 = $signed(p_Val2_6_fu_3395_p4);

assign tmp_134_cast_fu_2354_p2 = (tmp_78_fu_2348_p2 + tmp_77_fu_2344_p1);

assign tmp_139_cast_fu_3197_p1 = $signed(tmp_96_fu_3191_p2);

assign tmp_140_fu_2316_p2 = (r_V_3_fu_2164_p32 + r_V_2_fu_2110_p32);

assign tmp_141_fu_2334_p4 = {{x_V_fu_2322_p2[ap_const_lv32_3E : ap_const_lv32_4]}};

assign tmp_150_fu_2855_p1 = r_V_4_fu_2832_p14;

assign tmp_151_fu_2907_p2 = (tmp_150_fu_2855_p1 + x_V_2_fu_2802_p16);

assign tmp_152_fu_2925_p4 = {{x_V_3_fu_2913_p2[ap_const_lv32_3C : ap_const_lv32_10]}};

assign tmp_168_1_cast_fu_2700_p2 = (tmp_100_fu_2694_p2 + tmp_99_fu_2690_p1);

assign tmp_1703_s_fu_3174_p2 = (tmp_118_fu_3170_p2 + tmp_117_fu_3164_p2);

assign tmp_171_1_fu_3201_p3 = {{tmp_1703_s_reg_4631}, {1'b0}};

assign tmp_172_1_cast_fu_3218_p1 = $signed(tmp_172_1_fu_3212_p2);

assign tmp_172_1_fu_3212_p2 = (ap_const_lv9_40 - phitmp_1_cast_fu_3208_p1);

assign tmp_198_fu_1525_p1 = x_V_6_fu_1370_p2[1:0];

assign tmp_199_fu_2440_p1 = tmp_134_cast_fu_2354_p2[3:0];

assign tmp_217_fu_2662_p2 = (r_V_46_1_fu_2510_p32 + r_V_45_1_fu_2456_p32);

assign tmp_218_fu_2680_p4 = {{x_V_1_fu_2668_p2[ap_const_lv32_3E : ap_const_lv32_4]}};

assign tmp_227_fu_3018_p1 = r_V_47_1_fu_2995_p14;

assign tmp_228_fu_3070_p2 = (tmp_227_fu_3018_p1 + x_V_2_1_fu_2965_p16);

assign tmp_229_fu_3088_p4 = {{x_V_3_1_fu_3076_p2[ap_const_lv32_3C : ap_const_lv32_10]}};

assign tmp_230_fu_3352_p4 = {{kh_word_V_2_reg_4651[ap_const_lv32_3F : ap_const_lv32_30]}};

assign tmp_231_fu_3361_p4 = {{kh_word_V_2_reg_4651[ap_const_lv32_1F : ap_const_lv32_10]}};

assign tmp_232_fu_3370_p3 = ((kh_off_V_1_reg_4646[0:0] === 1'b1) ? tmp_230_fu_3352_p4 : tmp_231_fu_3361_p4);

assign tmp_278_fu_1946_p1 = x_V_6_1_fu_1791_p2[1:0];

assign tmp_279_fu_2786_p1 = tmp_168_1_cast_fu_2700_p2[3:0];

assign tmp_284_fu_3279_p1 = p_Val2_3_reg_506[9:0];

assign tmp_43_fu_573_p2 = (o_index_V + p_s_reg_482);

assign tmp_48_fu_609_p2 = ((layer_type_V == ap_const_lv2_3) ? 1'b1 : 1'b0);

assign tmp_50_fu_583_p4 = {{r_V_fu_578_p2[ap_const_lv32_10 : ap_const_lv32_7]}};

assign tmp_51_fu_593_p1 = tmp_50_fu_583_p4;

assign tmp_52_fu_675_p2 = ((p_5_reg_518 < n_inputs) ? 1'b1 : 1'b0);

assign tmp_54_fu_700_p1 = r_V_9_fu_690_p4;

assign tmp_55_fu_718_p1 = p_0856_s_fu_708_p4;

assign tmp_74_fu_2218_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{ap_const_lv2_0}, {tmp_72_reg_4193}}}, {ap_const_lv2_0}}}, {tmp_73_reg_4199}}}, {ap_const_lv2_0}}}, {tmp_76_reg_4205}}}, {ap_const_lv2_0}}}, {tmp_83_reg_4211}}}, {ap_const_lv2_0}}}, {tmp_94_reg_4217}}}, {ap_const_lv2_0}}}, {tmp_130_reg_4223}}}, {ap_const_lv2_0}}}, {tmp_131_reg_4229}}}, {ap_const_lv2_0}}}, {tmp_132_reg_4235}}}, {ap_const_lv2_0}}}, {tmp_133_reg_4241}}}, {ap_const_lv2_0}}}, {tmp_134_reg_4247}}}, {ap_const_lv2_0}}}, {tmp_135_reg_4253}}}, {ap_const_lv2_0}}}, {tmp_136_reg_4259}}}, {ap_const_lv2_0}}}, {tmp_137_reg_4265}}}, {ap_const_lv2_0}}}, {tmp_138_reg_4271}}}, {ap_const_lv2_0}}}, {tmp_139_reg_4277}};

assign tmp_75_fu_2267_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{ap_const_lv2_0}, {tmp_57_reg_4097}}}, {ap_const_lv2_0}}}, {tmp_58_reg_4103}}}, {ap_const_lv2_0}}}, {tmp_59_reg_4109}}}, {ap_const_lv2_0}}}, {tmp_60_reg_4115}}}, {ap_const_lv2_0}}}, {tmp_61_reg_4121}}}, {ap_const_lv2_0}}}, {tmp_62_reg_4127}}}, {ap_const_lv2_0}}}, {tmp_63_reg_4133}}}, {ap_const_lv2_0}}}, {tmp_64_reg_4139}}}, {ap_const_lv2_0}}}, {tmp_65_reg_4145}}}, {ap_const_lv2_0}}}, {tmp_66_reg_4151}}}, {ap_const_lv2_0}}}, {tmp_67_reg_4157}}}, {ap_const_lv2_0}}}, {tmp_68_reg_4163}}}, {ap_const_lv2_0}}}, {tmp_69_reg_4169}}}, {ap_const_lv2_0}}}, {tmp_70_reg_4175}}}, {ap_const_lv2_0}}}, {tmp_198_reg_4181}};

assign tmp_77_fu_2344_p1 = tmp_141_fu_2334_p4;

assign tmp_78_fu_2348_p2 = (tmp_74_fu_2218_p31 + tmp_75_fu_2267_p31);

assign tmp_79_fu_2360_p4 = {{tmp_140_fu_2316_p2[ap_const_lv32_7 : ap_const_lv32_4]}};

assign tmp_80_fu_2450_p2 = (tmp_95_cast_fu_2328_p1 + tmp41_fu_2444_p2);

assign tmp_81_fu_2863_p13 = {{{{{{{{{{{{{{{{{{{{{{ap_const_lv3_0}, {tmp_143_reg_4482}}}, {ap_const_lv4_0}}}, {tmp_144_reg_4489}}}, {ap_const_lv4_0}}}, {tmp_146_reg_4497}}}, {ap_const_lv4_0}}}, {tmp_147_reg_4505}}}, {ap_const_lv4_0}}}, {tmp_148_reg_4513}}}, {ap_const_lv4_0}}}, {tmp_149_reg_4521}};

assign tmp_82_fu_2885_p13 = {{{{{{{{{{{{{{{{{{{{{{ap_const_lv3_0}, {tmp_144_reg_4489}}}, {ap_const_lv4_0}}}, {tmp_146_reg_4497}}}, {ap_const_lv4_0}}}, {tmp_147_reg_4505}}}, {ap_const_lv4_0}}}, {tmp_148_reg_4513}}}, {ap_const_lv4_0}}}, {tmp_149_reg_4521}}}, {ap_const_lv4_0}}}, {tmp_199_reg_4530}};

assign tmp_84_fu_3308_p1 = r_V_10_fu_3298_p4;

assign tmp_85_fu_3128_p3 = {{ap_const_lv3_0}, {ap_pipeline_reg_pp0_iter4_tmp_149_reg_4521}};

assign tmp_86_fu_3317_p2 = ((kh_off_V_fu_3313_p1 == ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_87_fu_3248_p1 = r_V_11_fu_3238_p4;

assign tmp_88_fu_3135_p1 = ap_pipeline_reg_pp0_iter4_tmp_80_reg_4536;

assign tmp_91_fu_3138_p2 = (tmp_85_fu_3128_p3 + tmp_88_fu_3135_p1);

assign tmp_92_fu_3144_p2 = (tmp_89_reg_4606 + tmp_90_reg_4611);

assign tmp_93_fu_3148_p2 = (tmp_92_fu_3144_p2 + tmp_91_fu_3138_p2);

assign tmp_95_cast_fu_2328_p1 = tmp_139_reg_4277;

assign tmp_95_fu_3180_p3 = {{tmp_93_reg_4626}, {1'b0}};

assign tmp_96_cast_fu_2331_p1 = tmp_198_reg_4181;

assign tmp_96_fu_3191_p2 = (ap_const_lv9_40 - phitmp_cast_fu_3187_p1);

assign tmp_97_fu_2564_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{ap_const_lv2_0}, {tmp_169_reg_4385}}}, {ap_const_lv2_0}}}, {tmp_170_reg_4391}}}, {ap_const_lv2_0}}}, {tmp_172_reg_4397}}}, {ap_const_lv2_0}}}, {tmp_173_reg_4403}}}, {ap_const_lv2_0}}}, {tmp_174_reg_4409}}}, {ap_const_lv2_0}}}, {tmp_207_reg_4415}}}, {ap_const_lv2_0}}}, {tmp_208_reg_4421}}}, {ap_const_lv2_0}}}, {tmp_209_reg_4427}}}, {ap_const_lv2_0}}}, {tmp_210_reg_4433}}}, {ap_const_lv2_0}}}, {tmp_211_reg_4439}}}, {ap_const_lv2_0}}}, {tmp_212_reg_4445}}}, {ap_const_lv2_0}}}, {tmp_213_reg_4451}}}, {ap_const_lv2_0}}}, {tmp_214_reg_4457}}}, {ap_const_lv2_0}}}, {tmp_215_reg_4463}}}, {ap_const_lv2_0}}}, {tmp_216_reg_4469}};

assign tmp_98_fu_2613_p31 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{ap_const_lv2_0}, {tmp_154_reg_4289}}}, {ap_const_lv2_0}}}, {tmp_155_reg_4295}}}, {ap_const_lv2_0}}}, {tmp_156_reg_4301}}}, {ap_const_lv2_0}}}, {tmp_157_reg_4307}}}, {ap_const_lv2_0}}}, {tmp_158_reg_4313}}}, {ap_const_lv2_0}}}, {tmp_159_reg_4319}}}, {ap_const_lv2_0}}}, {tmp_160_reg_4325}}}, {ap_const_lv2_0}}}, {tmp_161_reg_4331}}}, {ap_const_lv2_0}}}, {tmp_162_reg_4337}}}, {ap_const_lv2_0}}}, {tmp_163_reg_4343}}}, {ap_const_lv2_0}}}, {tmp_164_reg_4349}}}, {ap_const_lv2_0}}}, {tmp_165_reg_4355}}}, {ap_const_lv2_0}}}, {tmp_166_reg_4361}}}, {ap_const_lv2_0}}}, {tmp_167_reg_4367}}}, {ap_const_lv2_0}}}, {tmp_278_reg_4373}};

assign tmp_99_fu_2690_p1 = tmp_218_fu_2680_p4;

assign tmp_fu_529_p2 = ((layer_type_V == ap_const_lv2_2) ? 1'b1 : 1'b0);

assign tmp_s_fu_549_p1 = n_inputs;

assign wt_mem_0_V_address0 = tmp_55_fu_718_p1;

assign wt_mem_1_V_address0 = tmp_55_fu_718_p1;

assign x_V_1_fu_2668_p2 = (r_V_45_1_cast_fu_2506_p1 + r_V_46_1_cast_fu_2560_p1);

assign x_V_2_1_cast_fu_2991_p1 = x_V_2_1_fu_2965_p16;

assign x_V_2_1_fu_2965_p16 = {{{{{{{{{{{{{{{tmp_219_reg_4541}, {ap_const_lv4_0}}, {tmp_220_reg_4547}}, {ap_const_lv4_0}}, {tmp_221_reg_4554}}, {ap_const_lv4_0}}, {tmp_223_reg_4562}}, {ap_const_lv4_0}}, {tmp_224_reg_4570}}, {ap_const_lv4_0}}, {tmp_225_reg_4578}}, {ap_const_lv4_0}}, {tmp_226_reg_4586}}, {ap_const_lv4_0}}, {tmp_279_reg_4595}};

assign x_V_2_cast_fu_2828_p1 = x_V_2_fu_2802_p16;

assign x_V_2_fu_2802_p16 = {{{{{{{{{{{{{{{tmp_142_reg_4476}, {ap_const_lv4_0}}, {tmp_143_reg_4482}}, {ap_const_lv4_0}}, {tmp_144_reg_4489}}, {ap_const_lv4_0}}, {tmp_146_reg_4497}}, {ap_const_lv4_0}}, {tmp_147_reg_4505}}, {ap_const_lv4_0}}, {tmp_148_reg_4513}}, {ap_const_lv4_0}}, {tmp_149_reg_4521}}, {ap_const_lv4_0}}, {tmp_199_reg_4530}};

assign x_V_3_1_cast_fu_3082_p2 = (tmp_103_fu_3026_p13 + tmp_104_fu_3048_p13);

assign x_V_3_1_fu_3076_p2 = (x_V_2_1_cast_fu_2991_p1 + r_V_47_1_cast_fu_3022_p1);

assign x_V_3_cast_fu_2919_p2 = (tmp_81_fu_2863_p13 + tmp_82_fu_2885_p13);

assign x_V_3_fu_2913_p2 = (x_V_2_cast_fu_2828_p1 + r_V_4_cast_fu_2859_p1);

assign x_V_4_1_fu_3102_p2 = (x_V_3_1_cast_fu_3082_p2 + r_V_48_1_cast_fu_3098_p1);

assign x_V_4_fu_2939_p2 = (x_V_3_cast_fu_2919_p2 + r_V_5_cast_fu_2935_p1);

assign x_V_6_1_fu_1791_p2 = (r_V_49_1_reg_3927 - r_V_44_1_cast_fu_1787_p1);

assign x_V_6_fu_1370_p2 = (r_V_s_reg_3762 - r_V_1_cast_fu_1366_p1);

assign x_V_fu_2322_p2 = (r_V_2_cast_fu_2160_p1 + r_V_3_cast_fu_2214_p1);

always @ (posedge ap_clk) begin
    lhs_V_reg_3648[16] <= 1'b0;
    tmp_s_reg_3663[21:16] <= 6'b000000;
end

endmodule //bin_dense
