# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/kh_i/kh_i.xci
# IP: The module: 'kh_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/kh_i/kh_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kh_i'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/kh_i/kh_i.xci
# IP: The module: 'kh_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/kh_i/kh_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kh_i'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
