// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k325tffg900-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.950000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=114,HLS_SYN_DSP=4,HLS_SYN_FF=20313,HLS_SYN_LUT=54344}" *)

module top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        wt_i_V_address0,
        wt_i_V_ce0,
        wt_i_V_q0,
        kh_i_V_address0,
        kh_i_V_ce0,
        kh_i_V_q0,
        dmem_i_V_address0,
        dmem_i_V_ce0,
        dmem_i_V_q0,
        dmem_o_V_address0,
        dmem_o_V_ce0,
        dmem_o_V_we0,
        dmem_o_V_d0,
        n_inputs_V,
        n_outputs_V,
        input_words_V,
        output_words_V,
        layer_mode_V,
        dmem_mode_V,
        width_mode_V,
        norm_mode_V
);

parameter    ap_ST_fsm_state1 = 13'b1;
parameter    ap_ST_fsm_pp0_stage0 = 13'b10;
parameter    ap_ST_fsm_state4 = 13'b100;
parameter    ap_ST_fsm_pp1_stage0 = 13'b1000;
parameter    ap_ST_fsm_state7 = 13'b10000;
parameter    ap_ST_fsm_pp2_stage0 = 13'b100000;
parameter    ap_ST_fsm_state10 = 13'b1000000;
parameter    ap_ST_fsm_state11 = 13'b10000000;
parameter    ap_ST_fsm_state12 = 13'b100000000;
parameter    ap_ST_fsm_state13 = 13'b1000000000;
parameter    ap_ST_fsm_state14 = 13'b10000000000;
parameter    ap_ST_fsm_pp3_stage0 = 13'b100000000000;
parameter    ap_ST_fsm_state20 = 13'b1000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv13_0 = 13'b0000000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv13_124A = 13'b1001001001010;
parameter    ap_const_lv13_1 = 13'b1;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv7_40 = 7'b1000000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_3F = 32'b111111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] wt_i_V_address0;
output   wt_i_V_ce0;
input  [63:0] wt_i_V_q0;
output  [5:0] kh_i_V_address0;
output   kh_i_V_ce0;
input  [63:0] kh_i_V_q0;
output  [10:0] dmem_i_V_address0;
output   dmem_i_V_ce0;
input  [63:0] dmem_i_V_q0;
output  [6:0] dmem_o_V_address0;
output   dmem_o_V_ce0;
output   dmem_o_V_we0;
output  [63:0] dmem_o_V_d0;
input  [15:0] n_inputs_V;
input  [15:0] n_outputs_V;
input  [15:0] input_words_V;
input  [15:0] output_words_V;
input  [2:0] layer_mode_V;
input  [0:0] dmem_mode_V;
input  [1:0] width_mode_V;
input  [1:0] norm_mode_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg wt_i_V_ce0;
reg kh_i_V_ce0;
reg[10:0] dmem_i_V_address0;
reg dmem_i_V_ce0;
reg[6:0] dmem_o_V_address0;
reg dmem_o_V_ce0;
reg dmem_o_V_we0;
reg[63:0] dmem_o_V_d0;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [15:0] kh_index_V;
reg   [15:0] o_index_V;
reg   [5:0] kh_mem_V_address0;
reg    kh_mem_V_ce0;
reg    kh_mem_V_we0;
wire   [63:0] kh_mem_V_q0;
reg   [11:0] wt_mem_V_0_address0;
reg    wt_mem_V_0_ce0;
reg    wt_mem_V_0_we0;
wire   [63:0] wt_mem_V_0_q0;
reg   [11:0] wt_mem_V_1_address0;
reg    wt_mem_V_1_ce0;
reg    wt_mem_V_1_we0;
wire   [63:0] wt_mem_V_1_q0;
reg   [9:0] dmem_V_0_0_address0;
reg    dmem_V_0_0_ce0;
reg    dmem_V_0_0_we0;
reg   [63:0] dmem_V_0_0_d0;
wire   [63:0] dmem_V_0_0_q0;
reg   [9:0] dmem_V_0_1_address0;
reg    dmem_V_0_1_ce0;
reg    dmem_V_0_1_we0;
reg   [63:0] dmem_V_0_1_d0;
wire   [63:0] dmem_V_0_1_q0;
reg   [9:0] dmem_V_1_0_address0;
reg    dmem_V_1_0_ce0;
reg    dmem_V_1_0_we0;
reg   [63:0] dmem_V_1_0_d0;
wire   [63:0] dmem_V_1_0_q0;
reg   [9:0] dmem_V_1_1_address0;
reg    dmem_V_1_1_ce0;
reg    dmem_V_1_1_we0;
reg   [63:0] dmem_V_1_1_d0;
wire   [63:0] dmem_V_1_1_q0;
reg   [15:0] p_1_reg_536;
reg   [9:0] p_2_reg_547;
reg   [15:0] p_4_reg_558;
reg   [12:0] p_5_reg_569;
reg   [6:0] p_6_reg_580;
reg   [15:0] p_0583_2_reg_602;
reg   [9:0] p_0579_2_reg_613;
reg   [15:0] p_8_reg_625;
reg   [15:0] ap_pipeline_reg_pp3_iter1_p_8_reg_625;
wire   [0:0] ap_CS_fsm_pp3_stage0;
reg   [15:0] ap_pipeline_reg_pp3_iter2_p_8_reg_625;
reg   [15:0] ap_pipeline_reg_pp3_iter3_p_8_reg_625;
reg   [15:0] reg_737;
wire   [0:0] ap_CS_fsm_state10;
reg   [0:0] tmp_3_reg_1547;
reg   [0:0] tmp_5_reg_1556;
wire   [0:0] dmem_mode_V_read_read_fu_190_p2;
wire   [1:0] layer_type_V_fu_743_p4;
reg   [1:0] layer_type_V_reg_1519;
wire   [0:0] d_o_idx_V_fu_784_p2;
reg   [0:0] d_o_idx_V_reg_1527;
wire   [15:0] tmp_cast1_fu_798_p1;
reg   [15:0] tmp_cast1_reg_1536;
wire   [4:0] words_per_image_V_fu_806_p2;
reg   [4:0] words_per_image_V_reg_1541;
wire   [0:0] tmp_3_fu_812_p2;
wire   [10:0] tmp_4_cast_fu_818_p1;
reg   [10:0] tmp_4_cast_reg_1551;
wire   [0:0] tmp_5_fu_822_p2;
wire   [0:0] exitcond1_fu_828_p2;
wire   [0:0] ap_CS_fsm_pp0_stage0;
wire   [15:0] i_V_2_fu_833_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [9:0] r_V_10_fu_839_p1;
reg   [9:0] r_V_10_reg_1569;
reg   [14:0] r_V_6_reg_1574;
wire   [0:0] tmp_38_fu_858_p1;
reg   [0:0] tmp_38_reg_1584;
reg   [0:0] tmp_37_reg_1593;
wire   [16:0] r_V_3_fu_902_p2;
reg   [16:0] r_V_3_reg_1597;
wire   [0:0] tmp_35_fu_913_p1;
reg   [0:0] tmp_35_reg_1607;
wire   [15:0] p_s_fu_938_p3;
wire   [9:0] p_s_42_fu_946_p3;
wire   [0:0] tmp_6_fu_975_p2;
wire   [0:0] ap_CS_fsm_pp1_stage0;
wire   [12:0] i_V_fu_981_p2;
reg    ap_enable_reg_pp1_iter0;
reg   [11:0] r_V_reg_1630;
wire   [0:0] tmp_36_fu_1002_p1;
reg   [0:0] tmp_36_reg_1640;
wire   [0:0] tmp_9_fu_1011_p2;
reg   [0:0] tmp_9_reg_1644;
wire   [0:0] ap_CS_fsm_pp2_stage0;
wire   [6:0] i_V_1_fu_1017_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [63:0] tmp_16_fu_1023_p1;
reg   [63:0] tmp_16_reg_1653;
wire   [0:0] tmp_20_fu_1032_p2;
wire   [0:0] ap_CS_fsm_state11;
wire    grp_bin_dense_fu_691_ap_done;
wire    grp_fp_conv_fu_667_ap_done;
wire   [9:0] i_V_3_fu_1037_p2;
reg   [9:0] i_V_3_reg_1667;
wire   [1:0] off_V_fu_1058_p1;
reg   [1:0] off_V_reg_1677;
wire   [0:0] this_assign_1_fu_1062_p2;
reg   [0:0] this_assign_1_reg_1684;
wire   [19:0] rhs_V_1_cast_fu_1104_p1;
reg   [19:0] rhs_V_1_cast_reg_1689;
wire   [10:0] tmp_32_cast_fu_1108_p1;
reg   [10:0] tmp_32_cast_reg_1694;
wire   [0:0] brmerge1_fu_1136_p2;
reg   [0:0] brmerge1_reg_1699;
wire   [15:0] nc_V_fu_1243_p3;
reg   [15:0] nc_V_reg_1703;
wire   [0:0] ap_CS_fsm_state12;
wire   [0:0] ap_CS_fsm_state13;
wire   [0:0] exitcond_fu_1275_p2;
reg   [0:0] exitcond_reg_1713;
wire   [15:0] i_V_4_fu_1280_p2;
reg   [15:0] i_V_4_reg_1717;
reg    ap_enable_reg_pp3_iter0;
wire   [0:0] tmp_43_fu_1300_p1;
reg   [0:0] tmp_43_reg_1727;
reg   [0:0] ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727;
reg   [0:0] ap_pipeline_reg_pp3_iter2_tmp_43_reg_1727;
wire   [15:0] p_0583_2_46_fu_1325_p3;
wire   [9:0] p_3_fu_1333_p3;
reg   [9:0] p_3_reg_1739;
wire   [19:0] grp_fu_1461_p3;
reg   [19:0] r_V_9_reg_1744;
reg    ap_enable_reg_pp3_iter1;
wire   [63:0] newSel8_fu_1400_p3;
reg   [63:0] newSel8_reg_1789;
wire   [63:0] newSel5_fu_1443_p3;
reg   [63:0] newSel5_reg_1794;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] ap_CS_fsm_state4;
reg    ap_enable_reg_pp1_iter1;
wire   [0:0] ap_CS_fsm_state7;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp3_iter2;
reg    ap_enable_reg_pp3_iter3;
reg    ap_enable_reg_pp3_iter4;
wire    grp_bin_conv_fu_637_ap_start;
wire    grp_bin_conv_fu_637_ap_done;
wire    grp_bin_conv_fu_637_ap_idle;
wire    grp_bin_conv_fu_637_ap_ready;
wire   [11:0] grp_bin_conv_fu_637_wt_mem_0_V_address0;
wire    grp_bin_conv_fu_637_wt_mem_0_V_ce0;
wire   [11:0] grp_bin_conv_fu_637_wt_mem_1_V_address0;
wire    grp_bin_conv_fu_637_wt_mem_1_V_ce0;
wire   [9:0] grp_bin_conv_fu_637_dmem_0_0_V_address0;
wire    grp_bin_conv_fu_637_dmem_0_0_V_ce0;
wire    grp_bin_conv_fu_637_dmem_0_0_V_we0;
wire   [63:0] grp_bin_conv_fu_637_dmem_0_0_V_d0;
wire   [9:0] grp_bin_conv_fu_637_dmem_0_1_V_address0;
wire    grp_bin_conv_fu_637_dmem_0_1_V_ce0;
wire    grp_bin_conv_fu_637_dmem_0_1_V_we0;
wire   [63:0] grp_bin_conv_fu_637_dmem_0_1_V_d0;
wire   [9:0] grp_bin_conv_fu_637_dmem_1_0_V_address0;
wire    grp_bin_conv_fu_637_dmem_1_0_V_ce0;
wire    grp_bin_conv_fu_637_dmem_1_0_V_we0;
wire   [63:0] grp_bin_conv_fu_637_dmem_1_0_V_d0;
wire   [9:0] grp_bin_conv_fu_637_dmem_1_1_V_address0;
wire    grp_bin_conv_fu_637_dmem_1_1_V_ce0;
wire    grp_bin_conv_fu_637_dmem_1_1_V_we0;
wire   [63:0] grp_bin_conv_fu_637_dmem_1_1_V_d0;
wire    grp_fp_conv_fu_667_ap_start;
wire    grp_fp_conv_fu_667_ap_idle;
wire    grp_fp_conv_fu_667_ap_ready;
wire   [11:0] grp_fp_conv_fu_667_wt_mem_0_V_address0;
wire    grp_fp_conv_fu_667_wt_mem_0_V_ce0;
wire   [11:0] grp_fp_conv_fu_667_wt_mem_1_V_address0;
wire    grp_fp_conv_fu_667_wt_mem_1_V_ce0;
wire   [5:0] grp_fp_conv_fu_667_kh_mem_V_address0;
wire    grp_fp_conv_fu_667_kh_mem_V_ce0;
wire   [9:0] grp_fp_conv_fu_667_dmem_0_0_V_address0;
wire    grp_fp_conv_fu_667_dmem_0_0_V_ce0;
wire    grp_fp_conv_fu_667_dmem_0_0_V_we0;
wire   [63:0] grp_fp_conv_fu_667_dmem_0_0_V_d0;
wire   [9:0] grp_fp_conv_fu_667_dmem_0_1_V_address0;
wire    grp_fp_conv_fu_667_dmem_0_1_V_ce0;
wire    grp_fp_conv_fu_667_dmem_0_1_V_we0;
wire   [63:0] grp_fp_conv_fu_667_dmem_0_1_V_d0;
wire   [9:0] grp_fp_conv_fu_667_dmem_1_0_V_address0;
wire    grp_fp_conv_fu_667_dmem_1_0_V_ce0;
wire    grp_fp_conv_fu_667_dmem_1_0_V_we0;
wire   [63:0] grp_fp_conv_fu_667_dmem_1_0_V_d0;
wire   [9:0] grp_fp_conv_fu_667_dmem_1_1_V_address0;
wire    grp_fp_conv_fu_667_dmem_1_1_V_ce0;
wire    grp_fp_conv_fu_667_dmem_1_1_V_we0;
wire   [63:0] grp_fp_conv_fu_667_dmem_1_1_V_d0;
wire    grp_bin_dense_fu_691_ap_start;
wire    grp_bin_dense_fu_691_ap_idle;
wire    grp_bin_dense_fu_691_ap_ready;
wire   [11:0] grp_bin_dense_fu_691_wt_mem_0_V_address0;
wire    grp_bin_dense_fu_691_wt_mem_0_V_ce0;
wire   [11:0] grp_bin_dense_fu_691_wt_mem_1_V_address0;
wire    grp_bin_dense_fu_691_wt_mem_1_V_ce0;
wire   [5:0] grp_bin_dense_fu_691_kh_mem_V_address0;
wire    grp_bin_dense_fu_691_kh_mem_V_ce0;
wire   [9:0] grp_bin_dense_fu_691_dmem_0_0_V_address0;
wire    grp_bin_dense_fu_691_dmem_0_0_V_ce0;
wire    grp_bin_dense_fu_691_dmem_0_0_V_we0;
wire   [63:0] grp_bin_dense_fu_691_dmem_0_0_V_d0;
wire   [9:0] grp_bin_dense_fu_691_dmem_0_1_V_address0;
wire    grp_bin_dense_fu_691_dmem_0_1_V_ce0;
wire    grp_bin_dense_fu_691_dmem_0_1_V_we0;
wire   [63:0] grp_bin_dense_fu_691_dmem_0_1_V_d0;
wire   [9:0] grp_bin_dense_fu_691_dmem_1_0_V_address0;
wire    grp_bin_dense_fu_691_dmem_1_0_V_ce0;
wire    grp_bin_dense_fu_691_dmem_1_0_V_we0;
wire   [63:0] grp_bin_dense_fu_691_dmem_1_0_V_d0;
wire   [9:0] grp_bin_dense_fu_691_dmem_1_1_V_address0;
wire    grp_bin_dense_fu_691_dmem_1_1_V_ce0;
wire    grp_bin_dense_fu_691_dmem_1_1_V_we0;
wire   [63:0] grp_bin_dense_fu_691_dmem_1_1_V_d0;
wire   [0:0] tmp_33_fu_757_p1;
reg   [0:0] p_9_reg_525;
wire   [0:0] tmp_32_fu_753_p1;
reg   [9:0] p_7_reg_591;
wire   [0:0] ap_CS_fsm_state14;
reg   [9:0] p_0579_2_phi_fu_617_p4;
reg   [15:0] p_8_phi_fu_629_p4;
reg    ap_reg_grp_bin_conv_fu_637_ap_start;
reg    ap_reg_grp_fp_conv_fu_667_ap_start;
reg    ap_reg_grp_bin_dense_fu_691_ap_start;
wire   [63:0] tmp_14_fu_853_p1;
wire   [63:0] tmp_12_fu_862_p1;
wire   [63:0] tmp_4_fu_908_p1;
wire   [63:0] tmp_13_fu_954_p1;
wire   [63:0] tmp_11_fu_961_p1;
wire   [63:0] tmp_2_fu_968_p1;
wire   [63:0] tmp_10_fu_997_p1;
wire   [63:0] tmp_1_fu_1006_p1;
wire   [63:0] tmp_i_fu_1053_p1;
wire   [63:0] tmp_30_fu_1345_p1;
wire   [63:0] tmp_28_fu_1362_p1;
wire   [63:0] tmp_29_fu_1451_p1;
wire   [63:0] tmp_27_fu_1456_p1;
wire   [15:0] p_Result_s_fu_762_p1;
wire   [15:0] tmp_17_fu_1068_p2;
wire   [15:0] tmp_22_fu_1251_p2;
wire   [15:0] grp_fu_726_p2;
wire   [15:0] tmp_23_fu_1263_p2;
wire   [2:0] tmp_s_fu_790_p3;
wire   [4:0] tmp_cast_fu_802_p1;
wire   [14:0] r_V_s_fu_875_p4;
wire   [15:0] r_V_11_fu_885_p1;
wire   [15:0] r_V_2_fu_889_p2;
wire   [16:0] rhs_V_fu_898_p1;
wire   [16:0] lhs_V_fu_894_p1;
wire   [9:0] img_off_V_fu_917_p2;
wire   [10:0] tmp_34_cast_fu_923_p1;
wire   [0:0] tmp_24_fu_927_p2;
wire   [15:0] img_idx_V_fu_932_p2;
wire   [15:0] tmp_25_cast_fu_1028_p1;
wire   [13:0] r_V_8_fu_1043_p4;
wire   [2:0] sf_fu_1084_p4;
wire   [0:0] tmp_25_fu_1079_p2;
wire   [4:0] tmp_fu_1093_p1;
wire   [4:0] words_per_out_V_fu_1097_p3;
wire   [0:0] tmp_55_not_fu_1112_p2;
wire   [0:0] brmerge_fu_1117_p2;
wire   [0:0] tmp_41_fu_1123_p3;
wire   [0:0] brmerge_not_fu_1130_p2;
wire   [0:0] tmp_42_i_fu_1142_p2;
wire   [0:0] tmp_43_i_fu_1151_p2;
wire   [0:0] sel_tmp1_fu_1191_p2;
wire   [0:0] sel_tmp6_demorgan_fu_1203_p2;
wire   [0:0] tmp_44_i_fu_1166_p2;
wire   [0:0] sel_tmp6_fu_1209_p2;
wire   [0:0] sel_tmp7_fu_1215_p2;
wire   [15:0] loc_V_2_fu_1171_p4;
wire   [15:0] loc_V_1_fu_1156_p4;
wire   [0:0] sel_tmp2_fu_1197_p2;
wire   [15:0] loc_V_fu_1147_p1;
wire   [15:0] loc_V_3_fu_1181_p4;
wire   [0:0] or_cond_fu_1229_p2;
wire   [15:0] newSel_fu_1221_p3;
wire   [15:0] newSel1_fu_1235_p3;
wire   [14:0] r_V_1_fu_1286_p4;
wire   [9:0] img_off_V_1_fu_1304_p2;
wire   [10:0] tmp_40_cast_fu_1310_p1;
wire   [0:0] tmp_31_fu_1314_p2;
wire   [15:0] img_idx_V_1_fu_1319_p2;
wire   [14:0] r_V_7_fu_1352_p4;
wire   [0:0] sel_tmp4_fu_1370_p2;
wire   [0:0] sel_tmp8_fu_1380_p2;
wire   [0:0] sel_tmp5_fu_1375_p2;
wire   [63:0] newSel6_fu_1384_p3;
wire   [63:0] newSel7_fu_1392_p3;
wire   [0:0] tmp_42_fu_1407_p1;
wire   [0:0] sel_tmp9_fu_1411_p2;
wire   [0:0] sel_tmp3_fu_1422_p2;
wire   [0:0] sel_tmp_fu_1417_p2;
wire   [63:0] newSel3_fu_1427_p3;
wire   [63:0] newSel4_fu_1435_p3;
wire   [14:0] grp_fu_1461_p0;
wire   [4:0] grp_fu_1461_p1;
wire   [9:0] grp_fu_1461_p2;
wire   [0:0] ap_CS_fsm_state20;
reg   [12:0] ap_NS_fsm;
wire   [19:0] grp_fu_1461_p00;
wire   [19:0] grp_fu_1461_p20;
reg    ap_condition_254;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'b1;
#0 kh_index_V = 16'b0000000000000000;
#0 o_index_V = 16'b0000000000000000;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter3 = 1'b0;
#0 ap_enable_reg_pp3_iter4 = 1'b0;
#0 ap_reg_grp_bin_conv_fu_637_ap_start = 1'b0;
#0 ap_reg_grp_fp_conv_fu_667_ap_start = 1'b0;
#0 ap_reg_grp_bin_dense_fu_691_ap_start = 1'b0;
end

top_kh_mem_V #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kh_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kh_mem_V_address0),
    .ce0(kh_mem_V_ce0),
    .we0(kh_mem_V_we0),
    .d0(kh_i_V_q0),
    .q0(kh_mem_V_q0)
);

top_wt_mem_V_0 #(
    .DataWidth( 64 ),
    .AddressRange( 2341 ),
    .AddressWidth( 12 ))
wt_mem_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(wt_mem_V_0_address0),
    .ce0(wt_mem_V_0_ce0),
    .we0(wt_mem_V_0_we0),
    .d0(wt_i_V_q0),
    .q0(wt_mem_V_0_q0)
);

top_wt_mem_V_0 #(
    .DataWidth( 64 ),
    .AddressRange( 2341 ),
    .AddressWidth( 12 ))
wt_mem_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(wt_mem_V_1_address0),
    .ce0(wt_mem_V_1_ce0),
    .we0(wt_mem_V_1_we0),
    .d0(wt_i_V_q0),
    .q0(wt_mem_V_1_q0)
);

top_dmem_V_0_0 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_0_address0),
    .ce0(dmem_V_0_0_ce0),
    .we0(dmem_V_0_0_we0),
    .d0(dmem_V_0_0_d0),
    .q0(dmem_V_0_0_q0)
);

top_dmem_V_0_0 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_0_1_address0),
    .ce0(dmem_V_0_1_ce0),
    .we0(dmem_V_0_1_we0),
    .d0(dmem_V_0_1_d0),
    .q0(dmem_V_0_1_q0)
);

top_dmem_V_0_0 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_0_address0),
    .ce0(dmem_V_1_0_ce0),
    .we0(dmem_V_1_0_we0),
    .d0(dmem_V_1_0_d0),
    .q0(dmem_V_1_0_q0)
);

top_dmem_V_0_0 #(
    .DataWidth( 64 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
dmem_V_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dmem_V_1_1_address0),
    .ce0(dmem_V_1_1_ce0),
    .we0(dmem_V_1_1_we0),
    .d0(dmem_V_1_1_d0),
    .q0(dmem_V_1_1_q0)
);

bin_conv grp_bin_conv_fu_637(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_conv_fu_637_ap_start),
    .ap_done(grp_bin_conv_fu_637_ap_done),
    .ap_idle(grp_bin_conv_fu_637_ap_idle),
    .ap_ready(grp_bin_conv_fu_637_ap_ready),
    .wt_mem_0_V_address0(grp_bin_conv_fu_637_wt_mem_0_V_address0),
    .wt_mem_0_V_ce0(grp_bin_conv_fu_637_wt_mem_0_V_ce0),
    .wt_mem_0_V_q0(wt_mem_V_0_q0),
    .wt_mem_1_V_address0(grp_bin_conv_fu_637_wt_mem_1_V_address0),
    .wt_mem_1_V_ce0(grp_bin_conv_fu_637_wt_mem_1_V_ce0),
    .wt_mem_1_V_q0(wt_mem_V_1_q0),
    .nc_V(nc_V_reg_1703),
    .dmem_0_0_V_address0(grp_bin_conv_fu_637_dmem_0_0_V_address0),
    .dmem_0_0_V_ce0(grp_bin_conv_fu_637_dmem_0_0_V_ce0),
    .dmem_0_0_V_we0(grp_bin_conv_fu_637_dmem_0_0_V_we0),
    .dmem_0_0_V_d0(grp_bin_conv_fu_637_dmem_0_0_V_d0),
    .dmem_0_0_V_q0(dmem_V_0_0_q0),
    .dmem_0_1_V_address0(grp_bin_conv_fu_637_dmem_0_1_V_address0),
    .dmem_0_1_V_ce0(grp_bin_conv_fu_637_dmem_0_1_V_ce0),
    .dmem_0_1_V_we0(grp_bin_conv_fu_637_dmem_0_1_V_we0),
    .dmem_0_1_V_d0(grp_bin_conv_fu_637_dmem_0_1_V_d0),
    .dmem_0_1_V_q0(dmem_V_0_1_q0),
    .dmem_1_0_V_address0(grp_bin_conv_fu_637_dmem_1_0_V_address0),
    .dmem_1_0_V_ce0(grp_bin_conv_fu_637_dmem_1_0_V_ce0),
    .dmem_1_0_V_we0(grp_bin_conv_fu_637_dmem_1_0_V_we0),
    .dmem_1_0_V_d0(grp_bin_conv_fu_637_dmem_1_0_V_d0),
    .dmem_1_0_V_q0(dmem_V_1_0_q0),
    .dmem_1_1_V_address0(grp_bin_conv_fu_637_dmem_1_1_V_address0),
    .dmem_1_1_V_ce0(grp_bin_conv_fu_637_dmem_1_1_V_ce0),
    .dmem_1_1_V_we0(grp_bin_conv_fu_637_dmem_1_1_V_we0),
    .dmem_1_1_V_d0(grp_bin_conv_fu_637_dmem_1_1_V_d0),
    .dmem_1_1_V_q0(dmem_V_1_1_q0),
    .d_i_idx_V(dmem_mode_V),
    .d_o_idx_V(d_o_idx_V_reg_1527),
    .n_inputs(n_inputs_V),
    .o_index_V(o_index_V),
    .new_batch_V(this_assign_1_reg_1684),
    .width_mode_V(width_mode_V),
    .norm_mode_V(norm_mode_V)
);

fp_conv grp_fp_conv_fu_667(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fp_conv_fu_667_ap_start),
    .ap_done(grp_fp_conv_fu_667_ap_done),
    .ap_idle(grp_fp_conv_fu_667_ap_idle),
    .ap_ready(grp_fp_conv_fu_667_ap_ready),
    .wt_mem_0_V_address0(grp_fp_conv_fu_667_wt_mem_0_V_address0),
    .wt_mem_0_V_ce0(grp_fp_conv_fu_667_wt_mem_0_V_ce0),
    .wt_mem_0_V_q0(wt_mem_V_0_q0),
    .wt_mem_1_V_address0(grp_fp_conv_fu_667_wt_mem_1_V_address0),
    .wt_mem_1_V_ce0(grp_fp_conv_fu_667_wt_mem_1_V_ce0),
    .wt_mem_1_V_q0(wt_mem_V_1_q0),
    .kh_mem_V_address0(grp_fp_conv_fu_667_kh_mem_V_address0),
    .kh_mem_V_ce0(grp_fp_conv_fu_667_kh_mem_V_ce0),
    .kh_mem_V_q0(kh_mem_V_q0),
    .dmem_0_0_V_address0(grp_fp_conv_fu_667_dmem_0_0_V_address0),
    .dmem_0_0_V_ce0(grp_fp_conv_fu_667_dmem_0_0_V_ce0),
    .dmem_0_0_V_we0(grp_fp_conv_fu_667_dmem_0_0_V_we0),
    .dmem_0_0_V_d0(grp_fp_conv_fu_667_dmem_0_0_V_d0),
    .dmem_0_0_V_q0(dmem_V_0_0_q0),
    .dmem_0_1_V_address0(grp_fp_conv_fu_667_dmem_0_1_V_address0),
    .dmem_0_1_V_ce0(grp_fp_conv_fu_667_dmem_0_1_V_ce0),
    .dmem_0_1_V_we0(grp_fp_conv_fu_667_dmem_0_1_V_we0),
    .dmem_0_1_V_d0(grp_fp_conv_fu_667_dmem_0_1_V_d0),
    .dmem_0_1_V_q0(dmem_V_0_1_q0),
    .dmem_1_0_V_address0(grp_fp_conv_fu_667_dmem_1_0_V_address0),
    .dmem_1_0_V_ce0(grp_fp_conv_fu_667_dmem_1_0_V_ce0),
    .dmem_1_0_V_we0(grp_fp_conv_fu_667_dmem_1_0_V_we0),
    .dmem_1_0_V_d0(grp_fp_conv_fu_667_dmem_1_0_V_d0),
    .dmem_1_0_V_q0(dmem_V_1_0_q0),
    .dmem_1_1_V_address0(grp_fp_conv_fu_667_dmem_1_1_V_address0),
    .dmem_1_1_V_ce0(grp_fp_conv_fu_667_dmem_1_1_V_ce0),
    .dmem_1_1_V_we0(grp_fp_conv_fu_667_dmem_1_1_V_we0),
    .dmem_1_1_V_d0(grp_fp_conv_fu_667_dmem_1_1_V_d0),
    .dmem_1_1_V_q0(dmem_V_1_1_q0),
    .d_i_idx_V(dmem_mode_V),
    .d_o_idx_V(d_o_idx_V_reg_1527),
    .kh_index_V(p_9_reg_525),
    .o_index_V(reg_737),
    .N(n_outputs_V)
);

bin_dense grp_bin_dense_fu_691(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bin_dense_fu_691_ap_start),
    .ap_done(grp_bin_dense_fu_691_ap_done),
    .ap_idle(grp_bin_dense_fu_691_ap_idle),
    .ap_ready(grp_bin_dense_fu_691_ap_ready),
    .wt_mem_0_V_address0(grp_bin_dense_fu_691_wt_mem_0_V_address0),
    .wt_mem_0_V_ce0(grp_bin_dense_fu_691_wt_mem_0_V_ce0),
    .wt_mem_0_V_q0(wt_mem_V_0_q0),
    .wt_mem_1_V_address0(grp_bin_dense_fu_691_wt_mem_1_V_address0),
    .wt_mem_1_V_ce0(grp_bin_dense_fu_691_wt_mem_1_V_ce0),
    .wt_mem_1_V_q0(wt_mem_V_1_q0),
    .kh_mem_V_address0(grp_bin_dense_fu_691_kh_mem_V_address0),
    .kh_mem_V_ce0(grp_bin_dense_fu_691_kh_mem_V_ce0),
    .kh_mem_V_q0(kh_mem_V_q0),
    .dmem_0_0_V_address0(grp_bin_dense_fu_691_dmem_0_0_V_address0),
    .dmem_0_0_V_ce0(grp_bin_dense_fu_691_dmem_0_0_V_ce0),
    .dmem_0_0_V_we0(grp_bin_dense_fu_691_dmem_0_0_V_we0),
    .dmem_0_0_V_d0(grp_bin_dense_fu_691_dmem_0_0_V_d0),
    .dmem_0_0_V_q0(dmem_V_0_0_q0),
    .dmem_0_1_V_address0(grp_bin_dense_fu_691_dmem_0_1_V_address0),
    .dmem_0_1_V_ce0(grp_bin_dense_fu_691_dmem_0_1_V_ce0),
    .dmem_0_1_V_we0(grp_bin_dense_fu_691_dmem_0_1_V_we0),
    .dmem_0_1_V_d0(grp_bin_dense_fu_691_dmem_0_1_V_d0),
    .dmem_0_1_V_q0(dmem_V_0_1_q0),
    .dmem_1_0_V_address0(grp_bin_dense_fu_691_dmem_1_0_V_address0),
    .dmem_1_0_V_ce0(grp_bin_dense_fu_691_dmem_1_0_V_ce0),
    .dmem_1_0_V_we0(grp_bin_dense_fu_691_dmem_1_0_V_we0),
    .dmem_1_0_V_d0(grp_bin_dense_fu_691_dmem_1_0_V_d0),
    .dmem_1_0_V_q0(dmem_V_1_0_q0),
    .dmem_1_1_V_address0(grp_bin_dense_fu_691_dmem_1_1_V_address0),
    .dmem_1_1_V_ce0(grp_bin_dense_fu_691_dmem_1_1_V_ce0),
    .dmem_1_1_V_we0(grp_bin_dense_fu_691_dmem_1_1_V_we0),
    .dmem_1_1_V_d0(grp_bin_dense_fu_691_dmem_1_1_V_d0),
    .dmem_1_1_V_q0(dmem_V_1_1_q0),
    .layer_type_V(layer_type_V_reg_1519),
    .d_i_idx_V(dmem_mode_V),
    .d_o_idx_V(d_o_idx_V_reg_1527),
    .o_index_V(reg_737),
    .n_inputs(n_inputs_V),
    .n_outputs(n_outputs_V)
);

top_mac_muladd_15bgk #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 20 ))
top_mac_muladd_15bgk_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1461_p0),
    .din1(grp_fu_1461_p1),
    .din2(grp_fu_1461_p2),
    .ce(1'b1),
    .dout(grp_fu_1461_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(1'b0 == exitcond1_fu_828_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == exitcond1_fu_828_p2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if ((((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(1'b0 == exitcond1_fu_828_p2)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage0) & ~(1'b0 == tmp_6_fu_975_p2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == tmp_6_fu_975_p2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b1;
        end else if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_pp1_stage0) & ~(1'b0 == tmp_6_fu_975_p2)))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp2_stage0) & ~(1'b0 == tmp_9_fu_1011_p2))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == tmp_9_fu_1011_p2))) begin
            ap_enable_reg_pp2_iter1 <= 1'b1;
        end else if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_pp2_stage0) & ~(1'b0 == tmp_9_fu_1011_p2)))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp3_stage0) & ~(1'b0 == exitcond_fu_1275_p2))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ((tmp_3_reg_1547 == 1'b0) | ~(1'b0 == tmp_5_reg_1556) | (1'b0 == tmp_20_fu_1032_p2)))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == exitcond_fu_1275_p2))) begin
            ap_enable_reg_pp3_iter1 <= 1'b1;
        end else if ((((1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ((tmp_3_reg_1547 == 1'b0) | ~(1'b0 == tmp_5_reg_1556) | (1'b0 == tmp_20_fu_1032_p2))) | ((1'b1 == ap_CS_fsm_pp3_stage0) & ~(1'b0 == exitcond_fu_1275_p2)))) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter3 <= 1'b0;
    end else begin
        ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter4 <= 1'b0;
    end else begin
        ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_bin_conv_fu_637_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_reg_grp_bin_conv_fu_637_ap_start <= 1'b1;
        end else if ((1'b1 == grp_bin_conv_fu_637_ap_ready)) begin
            ap_reg_grp_bin_conv_fu_637_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_bin_dense_fu_691_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & (tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556))) begin
            ap_reg_grp_bin_dense_fu_691_ap_start <= 1'b1;
        end else if ((1'b1 == grp_bin_dense_fu_691_ap_ready)) begin
            ap_reg_grp_bin_dense_fu_691_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_fp_conv_fu_667_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & ~(1'b0 == tmp_5_reg_1556))) begin
            ap_reg_grp_fp_conv_fu_667_ap_start <= 1'b1;
        end else if ((1'b1 == grp_fp_conv_fu_667_ap_ready)) begin
            ap_reg_grp_fp_conv_fu_667_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ~(1'b0 == grp_bin_conv_fu_637_ap_done))) begin
        kh_index_V <= tmp_22_fu_1251_p2;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))))) begin
        kh_index_V <= tmp_17_fu_1068_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0) & ~(1'b0 == tmp_32_fu_753_p1))) begin
        kh_index_V <= ap_const_lv16_0;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0) & (1'b0 == tmp_32_fu_753_p1))) begin
        kh_index_V <= p_Result_s_fu_762_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ~(1'b0 == grp_bin_conv_fu_637_ap_done))) begin
        o_index_V <= tmp_23_fu_1263_p2;
    end else if (((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done)))) | ((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done)))))) begin
        o_index_V <= grp_fu_726_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0) & ~(1'b0 == tmp_32_fu_753_p1))) begin
        o_index_V <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter1) & (1'b0 == exitcond_reg_1713))) begin
        p_0579_2_reg_613 <= p_3_reg_1739;
    end else if (((1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ((tmp_3_reg_1547 == 1'b0) | ~(1'b0 == tmp_5_reg_1556) | (1'b0 == tmp_20_fu_1032_p2)))) begin
        p_0579_2_reg_613 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter0) & (1'b0 == exitcond_fu_1275_p2))) begin
        p_0583_2_reg_602 <= p_0583_2_46_fu_1325_p3;
    end else if (((1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ((tmp_3_reg_1547 == 1'b0) | ~(1'b0 == tmp_5_reg_1556) | (1'b0 == tmp_20_fu_1032_p2)))) begin
        p_0583_2_reg_602 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond1_fu_828_p2))) begin
        p_1_reg_536 <= p_s_fu_938_p3;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        p_1_reg_536 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond1_fu_828_p2))) begin
        p_2_reg_547 <= p_s_42_fu_946_p3;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        p_2_reg_547 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond1_fu_828_p2))) begin
        p_4_reg_558 <= i_V_2_fu_833_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        p_4_reg_558 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_5_reg_569 <= ap_const_lv13_0;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0) & (1'b0 == tmp_6_fu_975_p2))) begin
        p_5_reg_569 <= i_V_fu_981_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_6_reg_580 <= ap_const_lv7_0;
    end else if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter0) & (1'b0 == tmp_9_fu_1011_p2))) begin
        p_6_reg_580 <= i_V_1_fu_1017_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'b0 == tmp_5_reg_1556) & ~(tmp_3_reg_1547 == 1'b0))) begin
        p_7_reg_591 <= ap_const_lv10_0;
    end else if (((1'b1 == ap_CS_fsm_state14) & ~(1'b0 == grp_bin_conv_fu_637_ap_done))) begin
        p_7_reg_591 <= i_V_3_reg_1667;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter1) & (1'b0 == exitcond_reg_1713))) begin
        p_8_reg_625 <= i_V_4_reg_1717;
    end else if (((1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ((tmp_3_reg_1547 == 1'b0) | ~(1'b0 == tmp_5_reg_1556) | (1'b0 == tmp_20_fu_1032_p2)))) begin
        p_8_reg_625 <= ap_const_lv16_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        if (~(1'b0 == tmp_32_fu_753_p1)) begin
            p_9_reg_525 <= 1'b0;
        end else if ((1'b0 == tmp_32_fu_753_p1)) begin
            p_9_reg_525 <= tmp_33_fu_757_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp3_stage0)) begin
        ap_pipeline_reg_pp3_iter1_p_8_reg_625 <= p_8_reg_625;
        ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727 <= tmp_43_reg_1727;
        exitcond_reg_1713 <= exitcond_fu_1275_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == 1'b1)) begin
        ap_pipeline_reg_pp3_iter2_p_8_reg_625 <= ap_pipeline_reg_pp3_iter1_p_8_reg_625;
        ap_pipeline_reg_pp3_iter2_tmp_43_reg_1727 <= ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727;
        ap_pipeline_reg_pp3_iter3_p_8_reg_625 <= ap_pipeline_reg_pp3_iter2_p_8_reg_625;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ((tmp_3_reg_1547 == 1'b0) | ~(1'b0 == tmp_5_reg_1556) | (1'b0 == tmp_20_fu_1032_p2)))) begin
        brmerge1_reg_1699 <= brmerge1_fu_1136_p2;
        rhs_V_1_cast_reg_1689[4 : 0] <= rhs_V_1_cast_fu_1104_p1[4 : 0];
        tmp_32_cast_reg_1694[4 : 0] <= tmp_32_cast_fu_1108_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        d_o_idx_V_reg_1527 <= d_o_idx_V_fu_784_p2;
        layer_type_V_reg_1519 <= {{layer_mode_V[ap_const_lv32_2 : ap_const_lv32_1]}};
        tmp_3_reg_1547 <= tmp_3_fu_812_p2;
        tmp_4_cast_reg_1551[4 : 0] <= tmp_4_cast_fu_818_p1[4 : 0];
        tmp_5_reg_1556 <= tmp_5_fu_822_p2;
        tmp_cast1_reg_1536[2 : 1] <= tmp_cast1_fu_798_p1[2 : 1];
        words_per_image_V_reg_1541 <= words_per_image_V_fu_806_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_5_reg_1556) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))))) begin
        i_V_3_reg_1667 <= i_V_3_fu_1037_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter0))) begin
        i_V_4_reg_1717 <= i_V_4_fu_1280_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        nc_V_reg_1703 <= nc_V_fu_1243_p3;
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b0 == brmerge1_reg_1699)) begin
        newSel5_reg_1794 <= newSel5_fu_1443_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == brmerge1_reg_1699)) begin
        newSel8_reg_1789 <= newSel8_fu_1400_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_5_reg_1556) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ~(1'b0 == tmp_20_fu_1032_p2))) begin
        off_V_reg_1677 <= off_V_fu_1058_p1;
        this_assign_1_reg_1684 <= this_assign_1_fu_1062_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter0) & (1'b0 == exitcond_fu_1275_p2))) begin
        p_3_reg_1739 <= p_3_fu_1333_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == exitcond1_fu_828_p2))) begin
        r_V_10_reg_1569 <= r_V_10_fu_839_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == exitcond1_fu_828_p2) & ~(tmp_3_reg_1547 == 1'b0))) begin
        r_V_3_reg_1597 <= r_V_3_fu_902_p2;
        tmp_35_reg_1607 <= tmp_35_fu_913_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == exitcond1_fu_828_p2))) begin
        r_V_6_reg_1574 <= {{p_4_reg_558[ap_const_lv32_F : ap_const_lv32_1]}};
        tmp_38_reg_1584 <= tmp_38_fu_858_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter1))) begin
        r_V_9_reg_1744 <= grp_fu_1461_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == tmp_6_fu_975_p2))) begin
        r_V_reg_1630 <= {{p_5_reg_569[ap_const_lv32_C : ap_const_lv32_1]}};
        tmp_36_reg_1640 <= tmp_36_fu_1002_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state10) & (tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556)) | ((1'b1 == ap_CS_fsm_state10) & ~(1'b0 == tmp_5_reg_1556)))) begin
        reg_737 <= o_index_V;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == tmp_9_fu_1011_p2))) begin
        tmp_16_reg_1653[6 : 0] <= tmp_16_fu_1023_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == exitcond1_fu_828_p2))) begin
        tmp_37_reg_1593 <= p_4_reg_558[ap_const_lv32_A];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == exitcond_fu_1275_p2) & (1'b0 == brmerge1_reg_1699))) begin
        tmp_43_reg_1727 <= tmp_43_fu_1300_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp2_stage0)) begin
        tmp_9_reg_1644 <= tmp_9_fu_1011_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_0_0_address0 = tmp_28_fu_1362_p1;
    end else if (((1'b0 == brmerge1_reg_1699) & (1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_0_0_address0 = tmp_30_fu_1345_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_35_reg_1607))) begin
        dmem_V_0_0_address0 = tmp_2_fu_968_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_37_reg_1593))) begin
        dmem_V_0_0_address0 = tmp_11_fu_961_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_38_reg_1584))) begin
        dmem_V_0_0_address0 = tmp_13_fu_954_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_address0 = grp_bin_dense_fu_691_dmem_0_0_V_address0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_address0 = grp_fp_conv_fu_667_dmem_0_0_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_0_address0 = grp_bin_conv_fu_637_dmem_0_0_V_address0;
    end else begin
        dmem_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == brmerge1_reg_1699) & (1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2)) | (~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2)) | ((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_38_reg_1584)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_37_reg_1593)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_35_reg_1607)))) begin
        dmem_V_0_0_ce0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_ce0 = grp_bin_dense_fu_691_dmem_0_0_V_ce0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_ce0 = grp_fp_conv_fu_667_dmem_0_0_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_0_ce0 = grp_bin_conv_fu_637_dmem_0_0_V_ce0;
    end else begin
        dmem_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_38_reg_1584)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_37_reg_1593)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_35_reg_1607)))) begin
        dmem_V_0_0_d0 = dmem_i_V_q0;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_d0 = grp_bin_dense_fu_691_dmem_0_0_V_d0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_d0 = grp_fp_conv_fu_667_dmem_0_0_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_0_d0 = grp_bin_conv_fu_637_dmem_0_0_V_d0;
    end else begin
        dmem_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_38_reg_1584)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_37_reg_1593)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & (1'b0 == tmp_35_reg_1607)))) begin
        dmem_V_0_0_we0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_we0 = grp_bin_dense_fu_691_dmem_0_0_V_we0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_0_we0 = grp_fp_conv_fu_667_dmem_0_0_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_0_we0 = grp_bin_conv_fu_637_dmem_0_0_V_we0;
    end else begin
        dmem_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_0_1_address0 = tmp_28_fu_1362_p1;
    end else if (((1'b0 == brmerge1_reg_1699) & ~(1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_0_1_address0 = tmp_30_fu_1345_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_35_reg_1607))) begin
        dmem_V_0_1_address0 = tmp_2_fu_968_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_37_reg_1593))) begin
        dmem_V_0_1_address0 = tmp_11_fu_961_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_38_reg_1584))) begin
        dmem_V_0_1_address0 = tmp_13_fu_954_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_address0 = grp_bin_dense_fu_691_dmem_0_1_V_address0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_address0 = grp_fp_conv_fu_667_dmem_0_1_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_1_address0 = grp_bin_conv_fu_637_dmem_0_1_V_address0;
    end else begin
        dmem_V_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == brmerge1_reg_1699) & ~(1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2)) | (~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2)) | ((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_38_reg_1584)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_37_reg_1593)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_35_reg_1607)))) begin
        dmem_V_0_1_ce0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_ce0 = grp_bin_dense_fu_691_dmem_0_1_V_ce0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_ce0 = grp_fp_conv_fu_667_dmem_0_1_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_1_ce0 = grp_bin_conv_fu_637_dmem_0_1_V_ce0;
    end else begin
        dmem_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_38_reg_1584)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_37_reg_1593)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_35_reg_1607)))) begin
        dmem_V_0_1_d0 = dmem_i_V_q0;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_d0 = grp_bin_dense_fu_691_dmem_0_1_V_d0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_d0 = grp_fp_conv_fu_667_dmem_0_1_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_1_d0 = grp_bin_conv_fu_637_dmem_0_1_V_d0;
    end else begin
        dmem_V_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_38_reg_1584)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_37_reg_1593)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == dmem_mode_V_read_read_fu_190_p2) & ~(1'b0 == tmp_35_reg_1607)))) begin
        dmem_V_0_1_we0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_we0 = grp_bin_dense_fu_691_dmem_0_1_V_we0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_0_1_we0 = grp_fp_conv_fu_667_dmem_0_1_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_0_1_we0 = grp_bin_conv_fu_637_dmem_0_1_V_we0;
    end else begin
        dmem_V_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_1_0_address0 = tmp_28_fu_1362_p1;
    end else if (((1'b0 == brmerge1_reg_1699) & (1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_1_0_address0 = tmp_30_fu_1345_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2))) begin
        dmem_V_1_0_address0 = tmp_2_fu_968_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2))) begin
        dmem_V_1_0_address0 = tmp_11_fu_961_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2))) begin
        dmem_V_1_0_address0 = tmp_13_fu_954_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_address0 = grp_bin_dense_fu_691_dmem_1_0_V_address0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_address0 = grp_fp_conv_fu_667_dmem_1_0_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_0_address0 = grp_bin_conv_fu_637_dmem_1_0_V_address0;
    end else begin
        dmem_V_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == brmerge1_reg_1699) & (1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2)) | (~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2)) | ((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)))) begin
        dmem_V_1_0_ce0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_ce0 = grp_bin_dense_fu_691_dmem_1_0_V_ce0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_ce0 = grp_fp_conv_fu_667_dmem_1_0_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_0_ce0 = grp_bin_conv_fu_637_dmem_1_0_V_ce0;
    end else begin
        dmem_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)))) begin
        dmem_V_1_0_d0 = dmem_i_V_q0;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_d0 = grp_bin_dense_fu_691_dmem_1_0_V_d0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_d0 = grp_fp_conv_fu_667_dmem_1_0_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_0_d0 = grp_bin_conv_fu_637_dmem_1_0_V_d0;
    end else begin
        dmem_V_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)))) begin
        dmem_V_1_0_we0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_we0 = grp_bin_dense_fu_691_dmem_1_0_V_we0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_0_we0 = grp_fp_conv_fu_667_dmem_1_0_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_0_we0 = grp_bin_conv_fu_637_dmem_1_0_V_we0;
    end else begin
        dmem_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_1_1_address0 = tmp_28_fu_1362_p1;
    end else if (((1'b0 == brmerge1_reg_1699) & ~(1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2))) begin
        dmem_V_1_1_address0 = tmp_30_fu_1345_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2))) begin
        dmem_V_1_1_address0 = tmp_2_fu_968_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2))) begin
        dmem_V_1_1_address0 = tmp_11_fu_961_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2))) begin
        dmem_V_1_1_address0 = tmp_13_fu_954_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_address0 = grp_bin_dense_fu_691_dmem_1_1_V_address0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_address0 = grp_fp_conv_fu_667_dmem_1_1_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_1_address0 = grp_bin_conv_fu_637_dmem_1_1_V_address0;
    end else begin
        dmem_V_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == brmerge1_reg_1699) & ~(1'b0 == ap_pipeline_reg_pp3_iter1_tmp_43_reg_1727) & (1'b1 == ap_enable_reg_pp3_iter2)) | (~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter2)) | ((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)))) begin
        dmem_V_1_1_ce0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_ce0 = grp_bin_dense_fu_691_dmem_1_1_V_ce0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_ce0 = grp_fp_conv_fu_667_dmem_1_1_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_1_ce0 = grp_bin_conv_fu_637_dmem_1_1_V_ce0;
    end else begin
        dmem_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)))) begin
        dmem_V_1_1_d0 = dmem_i_V_q0;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_d0 = grp_bin_dense_fu_691_dmem_1_1_V_d0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_d0 = grp_fp_conv_fu_667_dmem_1_1_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_1_d0 = grp_bin_conv_fu_637_dmem_1_1_V_d0;
    end else begin
        dmem_V_1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_38_reg_1584) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_37_reg_1593) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & ~(1'b0 == tmp_35_reg_1607) & ~(1'b0 == dmem_mode_V_read_read_fu_190_p2)))) begin
        dmem_V_1_1_we0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_we0 = grp_bin_dense_fu_691_dmem_1_1_V_we0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        dmem_V_1_1_we0 = grp_fp_conv_fu_667_dmem_1_1_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dmem_V_1_1_we0 = grp_bin_conv_fu_637_dmem_1_1_V_we0;
    end else begin
        dmem_V_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_condition_254 == 1'b1)) begin
        if (~(tmp_3_reg_1547 == 1'b0)) begin
            dmem_i_V_address0 = tmp_4_fu_908_p1;
        end else if (((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556))) begin
            dmem_i_V_address0 = tmp_12_fu_862_p1;
        end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556))) begin
            dmem_i_V_address0 = tmp_14_fu_853_p1;
        end else begin
            dmem_i_V_address0 = 'bx;
        end
    end else begin
        dmem_i_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond1_fu_828_p2)) | ((tmp_3_reg_1547 == 1'b0) & ~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond1_fu_828_p2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond1_fu_828_p2) & ~(tmp_3_reg_1547 == 1'b0)))) begin
        dmem_i_V_ce0 = 1'b1;
    end else begin
        dmem_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp3_iter4)) begin
        if (~(1'b0 == brmerge1_reg_1699)) begin
            dmem_o_V_address0 = tmp_27_fu_1456_p1;
        end else if ((1'b0 == brmerge1_reg_1699)) begin
            dmem_o_V_address0 = tmp_29_fu_1451_p1;
        end else begin
            dmem_o_V_address0 = 'bx;
        end
    end else begin
        dmem_o_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter4)) | (~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter4)))) begin
        dmem_o_V_ce0 = 1'b1;
    end else begin
        dmem_o_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp3_iter4)) begin
        if (~(1'b0 == brmerge1_reg_1699)) begin
            dmem_o_V_d0 = newSel5_reg_1794;
        end else if ((1'b0 == brmerge1_reg_1699)) begin
            dmem_o_V_d0 = newSel8_reg_1789;
        end else begin
            dmem_o_V_d0 = 'bx;
        end
    end else begin
        dmem_o_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter4)) | (~(1'b0 == brmerge1_reg_1699) & (1'b1 == ap_enable_reg_pp3_iter4)))) begin
        dmem_o_V_we0 = 1'b1;
    end else begin
        dmem_o_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter0))) begin
        kh_i_V_ce0 = 1'b1;
    end else begin
        kh_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == tmp_5_reg_1556) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_CS_fsm_state11) & ~(1'b0 == tmp_20_fu_1032_p2))) begin
        kh_mem_V_address0 = tmp_i_fu_1053_p1;
    end else if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1))) begin
        kh_mem_V_address0 = tmp_16_reg_1653;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        kh_mem_V_address0 = grp_bin_dense_fu_691_kh_mem_V_address0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        kh_mem_V_address0 = grp_fp_conv_fu_667_kh_mem_V_address0;
    end else begin
        kh_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == tmp_5_reg_1556) & ~(tmp_3_reg_1547 == 1'b0) & (1'b1 == ap_CS_fsm_state11) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ~(1'b0 == tmp_20_fu_1032_p2)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1)))) begin
        kh_mem_V_ce0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        kh_mem_V_ce0 = grp_bin_dense_fu_691_kh_mem_V_ce0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        kh_mem_V_ce0 = grp_fp_conv_fu_667_kh_mem_V_ce0;
    end else begin
        kh_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b0 == tmp_9_reg_1644))) begin
        kh_mem_V_we0 = 1'b1;
    end else begin
        kh_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter1) & (1'b0 == exitcond_reg_1713))) begin
        p_0579_2_phi_fu_617_p4 = p_3_reg_1739;
    end else begin
        p_0579_2_phi_fu_617_p4 = p_0579_2_reg_613;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_enable_reg_pp3_iter1) & (1'b0 == exitcond_reg_1713))) begin
        p_8_phi_fu_629_p4 = i_V_4_reg_1717;
    end else begin
        p_8_phi_fu_629_p4 = p_8_reg_625;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0))) begin
        wt_i_V_ce0 = 1'b1;
    end else begin
        wt_i_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1))) begin
        wt_mem_V_0_address0 = tmp_1_fu_1006_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_0_address0 = grp_bin_dense_fu_691_wt_mem_0_V_address0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_0_address0 = grp_fp_conv_fu_667_wt_mem_0_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        wt_mem_V_0_address0 = grp_bin_conv_fu_637_wt_mem_0_V_address0;
    end else begin
        wt_mem_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1))) begin
        wt_mem_V_0_ce0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_0_ce0 = grp_bin_dense_fu_691_wt_mem_0_V_ce0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_0_ce0 = grp_fp_conv_fu_667_wt_mem_0_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        wt_mem_V_0_ce0 = grp_bin_conv_fu_637_wt_mem_0_V_ce0;
    end else begin
        wt_mem_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b0 == tmp_36_reg_1640))) begin
        wt_mem_V_0_we0 = 1'b1;
    end else begin
        wt_mem_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1))) begin
        wt_mem_V_1_address0 = tmp_1_fu_1006_p1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_1_address0 = grp_bin_dense_fu_691_wt_mem_1_V_address0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_1_address0 = grp_fp_conv_fu_667_wt_mem_1_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        wt_mem_V_1_address0 = grp_bin_conv_fu_637_wt_mem_1_V_address0;
    end else begin
        wt_mem_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1))) begin
        wt_mem_V_1_ce0 = 1'b1;
    end else if (((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_1_ce0 = grp_bin_dense_fu_691_wt_mem_1_V_ce0;
    end else if ((~(1'b0 == tmp_5_reg_1556) & (1'b1 == ap_CS_fsm_state11))) begin
        wt_mem_V_1_ce0 = grp_fp_conv_fu_667_wt_mem_1_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        wt_mem_V_1_ce0 = grp_bin_conv_fu_637_wt_mem_1_V_ce0;
    end else begin
        wt_mem_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1) & ~(1'b0 == tmp_36_reg_1640))) begin
        wt_mem_V_1_we0 = 1'b1;
    end else begin
        wt_mem_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_enable_reg_pp0_iter0) & ~(1'b0 == exitcond1_fu_828_p2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b1 == ap_enable_reg_pp1_iter0) & ~(1'b0 == tmp_6_fu_975_p2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b1 == ap_enable_reg_pp2_iter0) & ~(1'b0 == tmp_9_fu_1011_p2))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if ((~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ((tmp_3_reg_1547 == 1'b0) | ~(1'b0 == tmp_5_reg_1556) | (1'b0 == tmp_20_fu_1032_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((1'b0 == tmp_5_reg_1556) & ~(tmp_3_reg_1547 == 1'b0) & ~(((tmp_3_reg_1547 == 1'b0) & (1'b0 == tmp_5_reg_1556) & (1'b0 == grp_bin_dense_fu_691_ap_done)) | (~(1'b0 == tmp_5_reg_1556) & (1'b0 == grp_fp_conv_fu_667_ap_done))) & ~(1'b0 == tmp_20_fu_1032_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (~(1'b0 == grp_bin_conv_fu_637_ap_done)) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp3_iter4) & ~(1'b1 == ap_enable_reg_pp3_iter3)) & ~((1'b1 == ap_enable_reg_pp3_iter0) & ~(1'b0 == exitcond_fu_1275_p2) & ~(1'b1 == ap_enable_reg_pp3_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((1'b1 == ap_enable_reg_pp3_iter0) & ~(1'b0 == exitcond_fu_1275_p2) & ~(1'b1 == ap_enable_reg_pp3_iter1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[ap_const_lv32_5];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[ap_const_lv32_B];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state10 = ap_CS_fsm[ap_const_lv32_6];

assign ap_CS_fsm_state11 = ap_CS_fsm[ap_const_lv32_7];

assign ap_CS_fsm_state12 = ap_CS_fsm[ap_const_lv32_8];

assign ap_CS_fsm_state13 = ap_CS_fsm[ap_const_lv32_9];

assign ap_CS_fsm_state14 = ap_CS_fsm[ap_const_lv32_A];

assign ap_CS_fsm_state20 = ap_CS_fsm[ap_const_lv32_C];

assign ap_CS_fsm_state4 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state7 = ap_CS_fsm[ap_const_lv32_4];

always @ (*) begin
    ap_condition_254 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond1_fu_828_p2));
end

assign brmerge1_fu_1136_p2 = (tmp_41_fu_1123_p3 | brmerge_not_fu_1130_p2);

assign brmerge_fu_1117_p2 = (tmp_55_not_fu_1112_p2 | tmp_25_fu_1079_p2);

assign brmerge_not_fu_1130_p2 = (brmerge_fu_1117_p2 ^ 1'b1);

assign d_o_idx_V_fu_784_p2 = (dmem_mode_V ^ 1'b1);

assign dmem_mode_V_read_read_fu_190_p2 = dmem_mode_V;

assign exitcond1_fu_828_p2 = ((p_4_reg_558 == input_words_V) ? 1'b1 : 1'b0);

assign exitcond_fu_1275_p2 = ((p_8_phi_fu_629_p4 == output_words_V) ? 1'b1 : 1'b0);

assign grp_bin_conv_fu_637_ap_start = ap_reg_grp_bin_conv_fu_637_ap_start;

assign grp_bin_dense_fu_691_ap_start = ap_reg_grp_bin_dense_fu_691_ap_start;

assign grp_fp_conv_fu_667_ap_start = ap_reg_grp_fp_conv_fu_667_ap_start;

assign grp_fu_1461_p0 = grp_fu_1461_p00;

assign grp_fu_1461_p00 = r_V_1_fu_1286_p4;

assign grp_fu_1461_p1 = rhs_V_1_cast_reg_1689;

assign grp_fu_1461_p2 = grp_fu_1461_p20;

assign grp_fu_1461_p20 = p_0579_2_reg_613;

assign grp_fu_726_p2 = (o_index_V + n_outputs_V);

assign i_V_1_fu_1017_p2 = (p_6_reg_580 + ap_const_lv7_1);

assign i_V_2_fu_833_p2 = (p_4_reg_558 + ap_const_lv16_1);

assign i_V_3_fu_1037_p2 = (p_7_reg_591 + ap_const_lv10_1);

assign i_V_4_fu_1280_p2 = (p_8_phi_fu_629_p4 + ap_const_lv16_1);

assign i_V_fu_981_p2 = (p_5_reg_569 + ap_const_lv13_1);

assign img_idx_V_1_fu_1319_p2 = (p_0583_2_reg_602 + ap_const_lv16_1);

assign img_idx_V_fu_932_p2 = (p_1_reg_536 + ap_const_lv16_1);

assign img_off_V_1_fu_1304_p2 = (p_0579_2_phi_fu_617_p4 + ap_const_lv10_1);

assign img_off_V_fu_917_p2 = (p_2_reg_547 + ap_const_lv10_1);

assign kh_i_V_address0 = tmp_16_fu_1023_p1;

assign layer_type_V_fu_743_p4 = {{layer_mode_V[ap_const_lv32_2 : ap_const_lv32_1]}};

assign lhs_V_fu_894_p1 = r_V_2_fu_889_p2;

assign loc_V_1_fu_1156_p4 = {{kh_mem_V_q0[ap_const_lv32_1F : ap_const_lv32_10]}};

assign loc_V_2_fu_1171_p4 = {{kh_mem_V_q0[ap_const_lv32_2F : ap_const_lv32_20]}};

assign loc_V_3_fu_1181_p4 = {{kh_mem_V_q0[ap_const_lv32_3F : ap_const_lv32_30]}};

assign loc_V_fu_1147_p1 = kh_mem_V_q0[15:0];

assign nc_V_fu_1243_p3 = ((or_cond_fu_1229_p2[0:0] === 1'b1) ? newSel_fu_1221_p3 : newSel1_fu_1235_p3);

assign newSel1_fu_1235_p3 = ((tmp_42_i_fu_1142_p2[0:0] === 1'b1) ? loc_V_fu_1147_p1 : loc_V_3_fu_1181_p4);

assign newSel3_fu_1427_p3 = ((sel_tmp3_fu_1422_p2[0:0] === 1'b1) ? dmem_V_1_1_q0 : dmem_V_0_1_q0);

assign newSel4_fu_1435_p3 = ((sel_tmp_fu_1417_p2[0:0] === 1'b1) ? dmem_V_0_0_q0 : dmem_V_1_0_q0);

assign newSel5_fu_1443_p3 = ((tmp_42_fu_1407_p1[0:0] === 1'b1) ? newSel3_fu_1427_p3 : newSel4_fu_1435_p3);

assign newSel6_fu_1384_p3 = ((sel_tmp8_fu_1380_p2[0:0] === 1'b1) ? dmem_V_1_1_q0 : dmem_V_0_1_q0);

assign newSel7_fu_1392_p3 = ((sel_tmp5_fu_1375_p2[0:0] === 1'b1) ? dmem_V_0_0_q0 : dmem_V_1_0_q0);

assign newSel8_fu_1400_p3 = ((ap_pipeline_reg_pp3_iter2_tmp_43_reg_1727[0:0] === 1'b1) ? newSel6_fu_1384_p3 : newSel7_fu_1392_p3);

assign newSel_fu_1221_p3 = ((sel_tmp7_fu_1215_p2[0:0] === 1'b1) ? loc_V_2_fu_1171_p4 : loc_V_1_fu_1156_p4);

assign off_V_fu_1058_p1 = kh_index_V[1:0];

assign or_cond_fu_1229_p2 = (sel_tmp7_fu_1215_p2 | sel_tmp2_fu_1197_p2);

assign p_0583_2_46_fu_1325_p3 = ((tmp_31_fu_1314_p2[0:0] === 1'b1) ? img_idx_V_1_fu_1319_p2 : p_0583_2_reg_602);

assign p_3_fu_1333_p3 = ((tmp_31_fu_1314_p2[0:0] === 1'b1) ? ap_const_lv10_0 : img_off_V_1_fu_1304_p2);

assign p_Result_s_fu_762_p1 = tmp_33_fu_757_p1;

assign p_s_42_fu_946_p3 = ((tmp_24_fu_927_p2[0:0] === 1'b1) ? ap_const_lv10_0 : img_off_V_fu_917_p2);

assign p_s_fu_938_p3 = ((tmp_24_fu_927_p2[0:0] === 1'b1) ? img_idx_V_fu_932_p2 : p_1_reg_536);

assign r_V_10_fu_839_p1 = p_4_reg_558[9:0];

assign r_V_11_fu_885_p1 = r_V_s_fu_875_p4;

assign r_V_1_fu_1286_p4 = {{p_0583_2_reg_602[ap_const_lv32_F : ap_const_lv32_1]}};

assign r_V_2_fu_889_p2 = r_V_11_fu_885_p1 << tmp_cast1_reg_1536;

assign r_V_3_fu_902_p2 = (rhs_V_fu_898_p1 + lhs_V_fu_894_p1);

assign r_V_7_fu_1352_p4 = {{ap_pipeline_reg_pp3_iter1_p_8_reg_625[ap_const_lv32_F : ap_const_lv32_1]}};

assign r_V_8_fu_1043_p4 = {{kh_index_V[ap_const_lv32_F : ap_const_lv32_2]}};

assign r_V_s_fu_875_p4 = {{p_1_reg_536[ap_const_lv32_F : ap_const_lv32_1]}};

assign rhs_V_1_cast_fu_1104_p1 = words_per_out_V_fu_1097_p3;

assign rhs_V_fu_898_p1 = p_2_reg_547;

assign sel_tmp1_fu_1191_p2 = (tmp_42_i_fu_1142_p2 ^ 1'b1);

assign sel_tmp2_fu_1197_p2 = (tmp_43_i_fu_1151_p2 & sel_tmp1_fu_1191_p2);

assign sel_tmp3_fu_1422_p2 = (tmp_42_fu_1407_p1 & d_o_idx_V_reg_1527);

assign sel_tmp4_fu_1370_p2 = (ap_pipeline_reg_pp3_iter2_tmp_43_reg_1727 ^ 1'b1);

assign sel_tmp5_fu_1375_p2 = (dmem_mode_V & sel_tmp4_fu_1370_p2);

assign sel_tmp6_demorgan_fu_1203_p2 = (tmp_42_i_fu_1142_p2 | tmp_43_i_fu_1151_p2);

assign sel_tmp6_fu_1209_p2 = (sel_tmp6_demorgan_fu_1203_p2 ^ 1'b1);

assign sel_tmp7_fu_1215_p2 = (tmp_44_i_fu_1166_p2 & sel_tmp6_fu_1209_p2);

assign sel_tmp8_fu_1380_p2 = (ap_pipeline_reg_pp3_iter2_tmp_43_reg_1727 & d_o_idx_V_reg_1527);

assign sel_tmp9_fu_1411_p2 = (tmp_42_fu_1407_p1 ^ 1'b1);

assign sel_tmp_fu_1417_p2 = (dmem_mode_V & sel_tmp9_fu_1411_p2);

assign sf_fu_1084_p4 = {{words_per_image_V_reg_1541[ap_const_lv32_4 : ap_const_lv32_2]}};

assign this_assign_1_fu_1062_p2 = ((p_7_reg_591 == ap_const_lv10_0) ? 1'b1 : 1'b0);

assign tmp_10_fu_997_p1 = p_5_reg_569;

assign tmp_11_fu_961_p1 = r_V_10_reg_1569;

assign tmp_12_fu_862_p1 = p_4_reg_558;

assign tmp_13_fu_954_p1 = r_V_6_reg_1574;

assign tmp_14_fu_853_p1 = p_4_reg_558;

assign tmp_16_fu_1023_p1 = p_6_reg_580;

assign tmp_17_fu_1068_p2 = (kh_index_V + n_outputs_V);

assign tmp_1_fu_1006_p1 = r_V_reg_1630;

assign tmp_20_fu_1032_p2 = ((tmp_25_cast_fu_1028_p1 < n_outputs_V) ? 1'b1 : 1'b0);

assign tmp_22_fu_1251_p2 = (ap_const_lv16_1 + kh_index_V);

assign tmp_23_fu_1263_p2 = (ap_const_lv16_1 + o_index_V);

assign tmp_24_fu_927_p2 = ((tmp_34_cast_fu_923_p1 == tmp_4_cast_reg_1551) ? 1'b1 : 1'b0);

assign tmp_25_cast_fu_1028_p1 = p_7_reg_591;

assign tmp_25_fu_1079_p2 = ((norm_mode_V != ap_const_lv2_2) ? 1'b1 : 1'b0);

assign tmp_27_fu_1456_p1 = ap_pipeline_reg_pp3_iter3_p_8_reg_625;

assign tmp_28_fu_1362_p1 = r_V_7_fu_1352_p4;

assign tmp_29_fu_1451_p1 = ap_pipeline_reg_pp3_iter3_p_8_reg_625;

assign tmp_2_fu_968_p1 = r_V_3_reg_1597;

assign tmp_30_fu_1345_p1 = r_V_9_reg_1744;

assign tmp_31_fu_1314_p2 = ((tmp_40_cast_fu_1310_p1 == tmp_32_cast_reg_1694) ? 1'b1 : 1'b0);

assign tmp_32_cast_fu_1108_p1 = words_per_out_V_fu_1097_p3;

assign tmp_32_fu_753_p1 = layer_mode_V[0:0];

assign tmp_33_fu_757_p1 = kh_index_V[0:0];

assign tmp_34_cast_fu_923_p1 = img_off_V_fu_917_p2;

assign tmp_35_fu_913_p1 = p_1_reg_536[0:0];

assign tmp_36_fu_1002_p1 = p_5_reg_569[0:0];

assign tmp_38_fu_858_p1 = p_4_reg_558[0:0];

assign tmp_3_fu_812_p2 = ((layer_type_V_fu_743_p4 == ap_const_lv2_1) ? 1'b1 : 1'b0);

assign tmp_40_cast_fu_1310_p1 = img_off_V_1_fu_1304_p2;

assign tmp_41_fu_1123_p3 = layer_mode_V[ap_const_lv32_2];

assign tmp_42_fu_1407_p1 = ap_pipeline_reg_pp3_iter2_p_8_reg_625[0:0];

assign tmp_42_i_fu_1142_p2 = ((off_V_reg_1677 == ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_43_fu_1300_p1 = p_0583_2_reg_602[0:0];

assign tmp_43_i_fu_1151_p2 = ((off_V_reg_1677 == ap_const_lv2_1) ? 1'b1 : 1'b0);

assign tmp_44_i_fu_1166_p2 = ((off_V_reg_1677 == ap_const_lv2_2) ? 1'b1 : 1'b0);

assign tmp_4_cast_fu_818_p1 = words_per_image_V_fu_806_p2;

assign tmp_4_fu_908_p1 = p_4_reg_558;

assign tmp_55_not_fu_1112_p2 = ((width_mode_V != ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_5_fu_822_p2 = ((layer_type_V_fu_743_p4 == ap_const_lv2_0) ? 1'b1 : 1'b0);

assign tmp_6_fu_975_p2 = ((p_5_reg_569 == ap_const_lv13_124A) ? 1'b1 : 1'b0);

assign tmp_9_fu_1011_p2 = ((p_6_reg_580 == ap_const_lv7_40) ? 1'b1 : 1'b0);

assign tmp_cast1_fu_798_p1 = tmp_s_fu_790_p3;

assign tmp_cast_fu_802_p1 = tmp_s_fu_790_p3;

assign tmp_fu_1093_p1 = sf_fu_1084_p4;

assign tmp_i_fu_1053_p1 = r_V_8_fu_1043_p4;

assign tmp_s_fu_790_p3 = {{width_mode_V}, {1'b0}};

assign words_per_image_V_fu_806_p2 = ap_const_lv5_1 << tmp_cast_fu_802_p1;

assign words_per_out_V_fu_1097_p3 = ((tmp_25_fu_1079_p2[0:0] === 1'b1) ? words_per_image_V_reg_1541 : tmp_fu_1093_p1);

assign wt_i_V_address0 = tmp_10_fu_997_p1;

always @ (posedge ap_clk) begin
    tmp_cast1_reg_1536[0] <= 1'b0;
    tmp_cast1_reg_1536[15:3] <= 13'b0000000000000;
    tmp_4_cast_reg_1551[10:5] <= 6'b000000;
    tmp_16_reg_1653[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    rhs_V_1_cast_reg_1689[19:5] <= 15'b000000000000000;
    tmp_32_cast_reg_1694[10:5] <= 6'b000000;
end

endmodule //top
