# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/bnn_accelerator/bnn_accelerator.xci
# IP: The module: 'bnn_accelerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/bnn_accelerator/constraints/top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_accelerator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/bnn_accelerator/bnn_accelerator.xci
# IP: The module: 'bnn_accelerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuzou/bnn-fpga-k7/VerilogPrj/VerilogPrj.srcs/sources_1/ip/bnn_accelerator/constraints/top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_accelerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
